// src/components/pages/Composer/CanvasTool.tsx
import { hasTooltip, Tooltip } from "$cmp/shared/Utility/Tooltip";


interface CanvasToolProps {
    onClick: () => void;
    tooltip?: string;
    ariaLabel?: string;
    style?: React.CSSProperties
    children: React.ReactNode;
}


export function CanvasTool({ children, tooltip, onClick, style, ariaLabel }: CanvasToolProps) {
    return <button 
        className={`tool ${hasTooltip(tooltip)}`} 
        onClick={onClick} 
        style={style}
        aria-label={ariaLabel}
    >
        {children}
        {tooltip &&
            <Tooltip>
                {tooltip}
            </Tooltip>
        }
    </button>
}

// src/lib/components/pages/Composer/CanvasTool.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { hasTooltip } from '$cmp/utility/tooltip';
  import Tooltip from '$cmp/utility/Tooltip.svelte';

  interface CanvasToolProps {
    onclick: () => void;
    tooltip?: string;
    ariaLabel?: string;
    style?: string;
    children: Snippet;
  }

  let { onclick, children, tooltip, style, ariaLabel }: CanvasToolProps = $props();
</script>

<button class={['tool', hasTooltip(tooltip)]} {onclick} {style} aria-label={ariaLabel}>
  {@render children()}
  {#if tooltip}
    <Tooltip>
      {tooltip}
    </Tooltip>
  {/if}
</button>
