// src/components/pages/Composer/ComposerKeyboard.tsx
import ComposerNote from "$cmp/pages/Composer/ComposerNote"
import {InstrumentData, NoteColumn} from "$lib/Songs/SongClasses"
import {NoteNameType, Pitch, TEMPO_CHANGERS} from "$config"
import {Instrument, ObservableNote} from "$lib/audio/Instrument"
import {ComposerSettingsDataType} from "$lib/BaseSettings"
import {FaChevronLeft, FaChevronRight} from "react-icons/fa"
import {useTheme} from "$lib/Hooks/useTheme"
import {AppButton} from "$cmp/shared/Inputs/AppButton";
import {Header} from "$cmp/shared/header/Header";
import {useTranslation} from "react-i18next";

interface ComposerKeyboardProps {
    data: {
        keyboard: Instrument
        instruments: InstrumentData[]
        isRecordingAudio: boolean
        currentLayer: number,
        currentColumn: NoteColumn,
        pitch: Pitch,
        settings: ComposerSettingsDataType
        isPlaying: boolean,
        noteNameType: NoteNameType
    },
    functions: {
        handleClick: (note: ObservableNote) => void
        startRecordingAudio: (override?: boolean) => void
        selectColumnFromDirection: (direction: number) => void
        handleTempoChanger: (tempoChanger: typeof TEMPO_CHANGERS[number]) => void
    }
}

export default function ComposerKeyboard({data, functions}: ComposerKeyboardProps) {
    const {t} = useTranslation('composer')
    const {keyboard, isPlaying, noteNameType, currentColumn, pitch, currentLayer, isRecordingAudio} = data
    const {handleClick, handleTempoChanger} = functions
    const [theme] = useTheme()
    if (keyboard === undefined) {
        return <div className="composer-keyboard-wrapper" style={{marginBottom: '4rem'}}>
            <h1>{t('error_with_this_layer')}</h1>
        </div>
    }
    if (isRecordingAudio) {
        return <div
            className="composer-keyboard-wrapper"
            style={{marginBottom: '4rem', flexDirection: 'column', alignItems: 'center'}}
        >
            <Header>
                {t('recording_audio')}...
            </Header>
            <AppButton onClick={() => functions.startRecordingAudio(false)} toggled>
                {t('stop_recording_audio')}
            </AppButton>
        </div>
    }
    let keyboardClass = "keyboard"
    if (keyboard.notes.length === 15) keyboardClass += " keyboard-5"
    if (keyboard.notes.length === 14) keyboardClass += " keyboard-5"
    if (keyboard.notes.length === 8) keyboardClass += " keyboard-4"
    if (keyboard.notes.length === 6) keyboardClass += " keyboard-3"

    return <>
        <div className="composer-keyboard-wrapper">
            {data.settings.useKeyboardSideButtons.value &&
                <button
                    onPointerDown={() => functions.selectColumnFromDirection(-1)}
                    className={`keyboard-column-selection-buttons ${!data.isPlaying ? 'keyboard-column-selection-buttons-visible' : ''}`}
                    style={{
                        paddingRight: '0.5rem',
                        justifyContent: "flex-end",
                        visibility: data.isPlaying ? 'hidden' : 'visible'
                    }}
                >
                    <FaChevronLeft/>
                </button>
            }
            <div
                className={keyboardClass}
            >
                {keyboard.notes.length === 0 ? <div className="loading">Loading...</div> : null}
                {keyboard.notes.map((note, i) => {
                    try {
                        const index = currentColumn.notes.findIndex((e) => e.index === i)

                        return <ComposerNote
                            key={note.index}
                            layer={(index >= 0
                                    ? currentColumn.notes[index].layer.toLayerStatus(currentLayer, data.instruments)
                                    : 0
                            )}
                            data={note}
                            theme={theme}
                            noteText={keyboard.getNoteText(i, noteNameType, pitch)}
                            instrument={keyboard.name}
                            noteImage={note.noteImage}
                            clickAction={handleClick}
                        />
                    } catch (e) {
                        return 'Err'
                    }
                })}
            </div>
            {data.settings.useKeyboardSideButtons.value &&
                <button
                    onPointerDown={() => functions.selectColumnFromDirection(1)}
                    className={`keyboard-column-selection-buttons ${!data.isPlaying ? 'keyboard-column-selection-buttons-visible' : ''}`}
                    style={{
                        paddingLeft: '0.5rem',
                        justifyContent: "flex-start",
                        visibility: data.isPlaying ? 'hidden' : 'visible'
                    }}
                >
                    <FaChevronRight/>
                </button>
            }
        </div>
        <div className={`tempo-changers-wrapper ${isPlaying ? "tempo-changers-wrapper-hidden" : ""}`}>
            <div className="bottom-right-text">
                {t('tempo')}
            </div>
            {TEMPO_CHANGERS.map((tempoChanger) => {
                return <button
                    key={tempoChanger.id}
                    onClick={() => handleTempoChanger(tempoChanger)}
                    style={{
                        ...(tempoChanger.changer === 1
                            ? {
                                backgroundColor: theme.get('primary').toString(),
                                color: theme.getText('primary').toString()
                            }
                            : {backgroundColor: "#" + tempoChanger.color.toString(16)})
                        ,
                        outline: data.currentColumn.tempoChanger === tempoChanger.id
                            ? `3px ${theme.get('composer_accent').toString()} solid`
                            : 'unset',
                        outlineOffset: '-3px'
                    }}
                >
                    {tempoChanger.text}
                </button>
            })}
        </div>
    </>
}

// src/lib/components/pages/Composer/ComposerKeyboard.svelte
<script lang="ts">
  import { game } from '$game';
  import { ThemeProvider } from '$core/theme/ThemeProvider.svelte';
  import type { NoteNameType, Pitch } from '$lib/games/types';
  import { computeRowLayerStatuses } from '$core/Songs/noteIds';
  import type { InstrumentData, NoteColumn } from '$core/Songs/SongClasses';
  import type { ComposerSettingsDataType } from '$core/BaseSettings';
  import type { Instrument, ObservableNote } from '$lib/audio/Instrument.svelte';
  import { t } from '$i18n/binding.svelte';
  import AppButton from '$cmp/inputs/AppButton.svelte';
  import Header from '$cmp/header/Header.svelte';
  import ShapeKeyboard from '$lib/games/shapes/ShapeKeyboard.svelte';
  import ComposerNote from './ComposerNote.svelte';

  let {
    data,
    functions,
  }: {
    data: {
      keyboard: Instrument;
      instruments: InstrumentData[];
      isRecordingAudio: boolean;
      currentLayer: number;
      currentColumn: NoteColumn;
      pitch: Pitch;
      settings: ComposerSettingsDataType;
      isPlaying: boolean;
      noteNameType: NoteNameType;
      heldButtons: Set<number>;
    };
    functions: {
      handleClick: (note: ObservableNote) => void;
      handleNoteRelease: (note: ObservableNote) => void;
      handleNoteLongPress: (note: ObservableNote, anchor: HTMLElement) => void;
      startRecordingAudio: (override?: boolean) => void;
      selectColumnFromDirection: (direction: number) => void;
      handleTempoChanger: (tempoChanger: (typeof game.composer.tempoChangers)[number]) => void;
    };
  } = $props();

  const layerStatuses = $derived.by(() => {
    try {
      return computeRowLayerStatuses(data.currentColumn.notes, data.currentLayer, data.instruments);
    } catch {
      return null;
    }
  });
</script>

{#snippet chevronLeftIcon()}
  <svg
    stroke="currentColor"
    fill="currentColor"
    stroke-width="0"
    viewBox="0 0 320 512"
    height="1em"
    width="1em"
    xmlns="http://www.w3.org/2000/svg"
    ><path
      d="M34.52 239.03L228.87 44.69c9.37-9.37 24.57-9.37 33.94 0l22.67 22.67c9.36 9.36 9.37 24.52.04 33.9L131.49 256l154.02 154.75c9.34 9.38 9.32 24.54-.04 33.9l-22.67 22.67c-9.37 9.37-24.57 9.37-33.94 0L34.52 272.97c-9.37-9.37-9.37-24.57 0-33.94z"
    /></svg
  >
{/snippet}

{#snippet chevronRightIcon()}
  <svg
    stroke="currentColor"
    fill="currentColor"
    stroke-width="0"
    viewBox="0 0 320 512"
    height="1em"
    width="1em"
    xmlns="http://www.w3.org/2000/svg"
    ><path
      d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z"
    /></svg
  >
{/snippet}

{#if data.keyboard === undefined}
  <div class="composer-keyboard-wrapper" style="margin-bottom:4rem">
    <h1>{t('composer:error_with_this_layer')}</h1>
  </div>
{:else if data.isRecordingAudio}
  <div
    class="composer-keyboard-wrapper"
    style="margin-bottom:4rem;flex-direction:column;align-items:center"
  >
    <Header>{t('composer:recording_audio')}...</Header>
    <AppButton onclick={() => functions.startRecordingAudio(false)} toggled>
      {t('composer:stop_recording_audio')}
    </AppButton>
  </div>
{:else}
  <div class="composer-keyboard-wrapper">
    {#if data.settings.useKeyboardSideButtons.value}
      <button
        onpointerdown={() => functions.selectColumnFromDirection(-1)}
        class={[
          'keyboard-column-selection-buttons',
          !data.isPlaying && 'keyboard-column-selection-buttons-visible',
        ]}
        style="padding-right:0.5rem;justify-content:flex-end;visibility:{data.isPlaying
          ? 'hidden'
          : 'visible'}"
      >
        {@render chevronLeftIcon()}
      </button>
    {/if}
    {#if data.keyboard.notes.length === 0}
      <div class="keyboard">
        <div class="loading">Loading...</div>
      </div>
    {:else}
      <ShapeKeyboard
        shape={data.keyboard.shape}
        count={data.keyboard.notes.length}
        class="keyboard"
      >
        {#snippet button(i)}
          {@const note = data.keyboard.notes[i]}
          {#if layerStatuses === null}
            Err
          {:else}
            <ComposerNote
              layer={layerStatuses.get(i) ?? 0}
              data={note}
              noteText={data.keyboard.getNoteText(i, data.noteNameType, data.pitch)}
              instrument={data.keyboard.name}
              noteImage={note.noteImage}
              clickAction={functions.handleClick}
              releaseAction={functions.handleNoteRelease}
              longPressAction={functions.handleNoteLongPress}
              held={data.heldButtons.has(i)}
            />
          {/if}
        {/snippet}
      </ShapeKeyboard>
    {/if}
    {#if data.settings.useKeyboardSideButtons.value}
      <button
        onpointerdown={() => functions.selectColumnFromDirection(1)}
        class={[
          'keyboard-column-selection-buttons',
          !data.isPlaying && 'keyboard-column-selection-buttons-visible',
        ]}
        style="padding-left:0.5rem;justify-content:flex-start;visibility:{data.isPlaying
          ? 'hidden'
          : 'visible'}"
      >
        {@render chevronRightIcon()}
      </button>
    {/if}
  </div>
  <div class={['tempo-changers-wrapper', data.isPlaying && 'tempo-changers-wrapper-hidden']}>
    <div class="bottom-right-text">
      {t('composer:tempo')}
    </div>
    {#each game.composer.tempoChangers as tempoChanger (tempoChanger.id)}
      <button
        onclick={() => functions.handleTempoChanger(tempoChanger)}
        style="{tempoChanger.changer === 1
          ? `background-color:${ThemeProvider.get('primary').toString()};color:${ThemeProvider.getText('primary').toString()}`
          : `background-color:#${tempoChanger.color.toString(16)}`};outline:{data.currentColumn
          .tempoChanger === tempoChanger.id
          ? `3px ${ThemeProvider.get('composer_accent').toString()} solid`
          : 'unset'};outline-offset:-3px"
      >
        {tempoChanger.text}
      </button>
    {/each}
  </div>
{/if}
