// src/pages/Composer/Components/ComposerNote.tsx
import { memo , useEffect, useState } from 'react'
import { NOTES_CSS_CLASSES, APP_NAME, INSTRUMENTS_DATA,BASE_THEME_CONFIG } from "appConfig"
import GenshinNoteBorder from 'components/GenshinNoteBorder'
import SvgNote from 'components/SvgNotes'
import { ThemeStore } from 'stores/ThemeStore'
import { observe } from 'mobx'
import { NoteImage } from 'types/Keyboard'
import { NoteData } from 'lib/Instrument'
import { CombinedLayer, InstrumentName } from 'types/GeneralTypes'

function getTextColor(){
    const noteBg = ThemeStore.get('note_background')
    if(APP_NAME === 'Genshin'){
        if(noteBg.luminosity() > 0.65){
            return BASE_THEME_CONFIG.text.note
        }else{
            return noteBg.isDark() ? BASE_THEME_CONFIG.text.light : BASE_THEME_CONFIG.text.dark
        }
    }else{
        return noteBg.isDark() ? BASE_THEME_CONFIG.text.light : BASE_THEME_CONFIG.text.dark
    }
}

interface ComposerNoteProps{
    data: NoteData
    layer: CombinedLayer
    instrument: InstrumentName
    clickAction: (data: NoteData) => void
    noteText: string
    noteImage: NoteImage
}
export default memo(function ComposerNote({ data, layer, instrument, clickAction, noteText, noteImage }: ComposerNoteProps) {
    const [textColor, setTextColor] = useState(getTextColor())
    useEffect(() => {
        const dispose = observe(ThemeStore.state.data,() => {
            setTextColor(getTextColor())
        })
        return dispose
    },[])

    let className = NOTES_CSS_CLASSES.noteComposer
    if (layer[0] === "1") className += " layer-1"
    if (layer[1] === "1") className += " layer-2"
    if (layer[2] === "1") className += " layer-3"
    if (layer[3] === "1") className += " layer-4"

    const color = ThemeStore.get('note_background').desaturate(0.6)
    const layer3Class = "Sky" ? "layer-3-ball-bigger" : "layer-3-ball"
    return <button onPointerDown={() => clickAction(data)} className="button-hitbox">
        <div className={className} >
            <SvgNote
                name={noteImage}
                color={ThemeStore.isDefault('accent') ? INSTRUMENTS_DATA[instrument]?.fill : undefined}
            />
            {APP_NAME === 'Genshin' && <GenshinNoteBorder
                fill={color.isDark() ? color.lighten(0.45).hex() : color.darken(0.18).hex()}
                className='genshin-border'
            />}
            <div className={layer3Class}>
            </div>
            <div className='layer-4-line'>
            </div>
            <div 
                className={APP_NAME === "Sky" ? "note-name-sky" : "note-name"}
                style={{color:textColor}}
            >
                {noteText}
            </div>
        </div>
    </button>
}, (p, n) => {
    return p.noteText === n.noteText && p.clickAction === n.clickAction && p.noteImage === n.noteImage
        && p.noteText === n.noteText && p.layer === n.layer && p.instrument === n.instrument
})

// src/lib/components/pages/Composer/ComposerNote.svelte
<script module lang="ts">
    import {game} from '$game'
    import type {LayerStatus} from '$core/Songs/Layer'

    // Precomputes a LayerStatus (bit pattern 0-15) -> CSS class string lookup, e.g. layer=5
    // (bits 1+3 set) -> "layer-1 layer-3".
    // QUIRK: the join emits empty tokens, so a layer=0 note's class string carries trailing spaces — reproduced byte-for-byte, do not normalise it. The map covers 0-15 only; LayerStatus also permits 16, which old never produced and this deliberately does not widen to.
    const classNameMap = new Map<LayerStatus, string>(
        new Array(16)
            .fill(0)
            .map((_, i) => {
                const layers = i.toString(2).split('').map(x => parseInt(x)).reverse()
                const className = `${game.notes.cssClasses.noteComposer} ${layers.map((x, idx) => x === 1 ? `layer-${idx + 1}` : '').join(' ')}`
                return [i as LayerStatus, className] as const
            })
    )
</script>

<script lang="ts">
    import {ThemeProvider} from '$core/theme/ThemeProvider.svelte'
    import {preventDefault} from '$core/utils/Utilities'
    import type {InstrumentName} from '$core/types'
    import type {ObservableNote} from '$lib/audio/Instrument.svelte'
    import type {NoteImage} from '$lib/games/types'
    import GenshinNoteBorder from '$cmp/GenshinNoteBorder.svelte'
    import SvgNote from '$cmp/SvgNote.svelte'

    let {
        data,
        layer,
        instrument,
        clickAction,
        noteText,
        noteImage,
    }: {
        data: ObservableNote
        layer: LayerStatus
        instrument: InstrumentName
        clickAction: (data: ObservableNote) => void
        noteText: string
        noteImage: NoteImage
    } = $props()

    let colors = $state({
        note_background: ThemeProvider.get('note_background').desaturate(0.6).toString(),
        isAccentDefault: ThemeProvider.isDefault('accent'),
    })

    $effect(() => {
        const color = ThemeProvider.get('note_background').desaturate(0.6)
        colors = {
            note_background: color.isDark() ? color.lighten(0.45).toString() : color.darken(0.18).toString(),
            isAccentDefault: ThemeProvider.isDefault('accent'),
        }
    })

    const className = $derived(classNameMap.get(layer) ?? game.notes.cssClasses.noteComposer)
</script>

<button
    onpointerdown={(e) => {
        preventDefault(e)
        clickAction(data)
    }}
    class="button-hitbox"
    oncontextmenu={preventDefault}
>
    <div class={className}>
        {#if game.features.hasNoteFrame}
            <GenshinNoteBorder fill={colors.note_background} class="genshin-border" />
        {/if}
        <SvgNote
            name={noteImage}
            color={colors.isAccentDefault ? game.instruments.data[instrument]?.fill : undefined}
            background="var(--note-background)"
        />
        <div class="layer-3-ball-bigger"></div>
        <div class="layer-4-line"></div>
        <div class={game.features.hasNoteFrame ? 'note-name' : 'note-name-sky'}>
            {noteText}
        </div>
    </div>
</button>
