// src/pages/Composer/Components/MultiSwitch.tsx
import { memo } from "react"

interface MultiSwitchProps{
    options: readonly number[] | readonly string[]
    selected: number | string
    buttonsClass: string
    onSelect: (index: number | string) => void
}


export default memo(function MultiSwitch({ options, selected, buttonsClass, onSelect }: MultiSwitchProps){
    return <>
        {options.map(index => {
            return <button
                style={selected === index ? {backgroundColor: 'var(--accent)', color: 'var(--accent-text)'}: {}}
                className={buttonsClass}
                onClick={() => onSelect(index)}
                key={index}
            >
                {index}
            </button>
        })}
    </>
},(p,n)=>{
    return p.options?.length === n.options?.length 
        && p.selected === n.selected
        && p.onSelect === n.onSelect
})

// src/lib/components/pages/Composer/MultiSwitch.svelte
<script lang="ts" generics="T extends string">
    // No consumers anywhere in this tree (verified) - dead code, not wired up to anything.
    let {
        options,
        selected,
        buttonsClass,
        onSelect,
    }: {
        options: readonly T[]
        selected: T
        buttonsClass?: string
        onSelect: (selected: T) => void
    } = $props()
</script>

{#each options as value, i (i)}
    <button
        style={selected === value ? 'background-color:var(--accent);color:var(--accent-text)' : ''}
        class={buttonsClass}
        onclick={() => onSelect(value)}
    >
        {value}
    </button>
{/each}
