// src/lib/components/layout/Row.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'
    import {justifyMap, type Justify} from './layoutConstants'

    // Old: src/components/shared/layout/Row.tsx
    interface RowProps {
        gap?: string
        flex1?: boolean
        justify?: Justify
        align?: Justify
        padding?: string
        className?: string
        style?: string
        children?: Snippet
    }

    let {children, className = '', style = '', gap, flex1, justify, align, padding}: RowProps = $props()

    const computedStyle = $derived([
        gap !== undefined ? `gap:${gap}` : '',
        flex1 ? 'flex:1' : '',
        justify !== undefined ? `justify-content:${justifyMap[justify]}` : '',
        align !== undefined ? `align-items:${justifyMap[align]}` : '',
        padding !== undefined ? `padding:${padding}` : '',
    ].filter(Boolean).join(';'))
</script>

<div class="row {className}" style="{computedStyle};{style}">
    {@render children?.()}
</div>

// src/components/shared/layout/Row.tsx
import {MaybeChildren, Stylable} from "$lib/UtilTypes";
import {Justify, justifyMap} from "$cmp/shared/layout/layoutConstants";


interface RowProps extends Stylable {
    gap?: string
    flex1?: boolean
    justify?: Justify
    align?: Justify
    padding?: string
}


export function Row({children, className, style, gap, flex1, justify, align, padding}: MaybeChildren<RowProps>) {
    return <div
        className={`row ${className ?? ""}`}
        style={{
            gap,
            flex: flex1 ? 1 : undefined,
            justifyContent: justify ? justifyMap[justify] : undefined,
            alignItems: align ? justifyMap[align] : undefined,
            padding: padding,
            ...style
        }}
    >
        {children}
    </div>
}
