// src/components/shared/Inputs/AppButton.tsx
import {hasTooltip, Tooltip, TooltipPosition} from "$cmp/shared/Utility/Tooltip"
import type {CSSProperties, MouseEvent, ReactNode} from 'react'

export interface AppButtonProps {
    style?: CSSProperties,
    className?: string,
    onClick?: (e: MouseEvent) => void,
    children?: ReactNode,
    toggled?: boolean,
    disabled?: boolean,
    visible?: boolean,
    cssVar?: string,
    tooltip?: string,
    tooltipPosition?: TooltipPosition
    ariaLabel?: string
}

export function AppButton({
                              style = {},
                              className = '',
                              cssVar,
                              children,
                              toggled = false,
                              onClick,
                              disabled = false,
                              visible = true,
                              tooltip,
                              ariaLabel,
                              tooltipPosition
                          }: AppButtonProps) {
    return <button
        className={`app-button ${className} ${toggled ? 'active' : ''} ${hasTooltip(tooltip)}`}
        style={{
            ...(cssVar && {backgroundColor: `var(--${cssVar})`, color: `var(--${cssVar}-text)`}),
            ...style,
            ...(!visible
                ? {display: 'none'}
                : {})
        }}
        aria-label={ariaLabel}
        onClick={onClick}
        disabled={disabled}
    >
        {children}
        {tooltip &&
            <Tooltip
                position={tooltipPosition}
            >
                {tooltip}
            </Tooltip>
        }
    </button>
}

// src/lib/components/inputs/AppButton.svelte
<script module lang="ts">
    import type {Snippet} from 'svelte'
    import type {TooltipPosition} from '../utility/tooltip'

    export interface AppButtonProps {
        style?: string
        className?: string
        onclick?: (e: MouseEvent) => void
        children?: Snippet
        toggled?: boolean
        disabled?: boolean
        visible?: boolean
        cssVar?: string
        tooltip?: string
        tooltipPosition?: TooltipPosition
        ariaLabel?: string
    }
</script>

<script lang="ts">
    import Tooltip from '../utility/Tooltip.svelte'
    import {hasTooltip} from '../utility/tooltip'

    // CSS (.app-button, .icon-app-button, .active, :disabled, etc.) lives in
    // global App.css.
    let {
        style = '',
        className = '',
        cssVar,
        children,
        toggled = false,
        onclick,
        disabled = false,
        visible = true,
        tooltip,
        ariaLabel,
        tooltipPosition,
    }: AppButtonProps = $props()

    const computedStyle = $derived([
        cssVar ? `background-color:var(--${cssVar});color:var(--${cssVar}-text)` : '',
        style,
        !visible ? 'display:none' : '',
    ].filter(Boolean).join(';'))
</script>

<button
    class="app-button {className} {toggled ? 'active' : ''} {hasTooltip(tooltip)}"
    style={computedStyle}
    aria-label={ariaLabel}
    {onclick}
    {disabled}
>
    {@render children?.()}
    {#if tooltip}
        <Tooltip position={tooltipPosition}>
            {tooltip}
        </Tooltip>
    {/if}
</button>
