// src/components/Settings/Select.tsx
import { ChangeEvent, ReactNode } from "react"
import { Theme } from "$stores/ThemeStore/ThemeProvider"
import { SettingsSelect, SettingUpdateKey } from "$types/SettingsPropriety"

interface SelectProps {
    value: string | number
    type: string | number
    data: SettingsSelect
    objectKey: SettingUpdateKey
    children: ReactNode
    theme: Theme
    onChange: (data: {
        key: SettingUpdateKey
        data: any
    }) => void
}
export function Select({ value, onChange, data, objectKey , children, theme, type}: SelectProps) {
    function handleChange(e: ChangeEvent<HTMLSelectElement>) {
        onChange({
            key: objectKey,
            data: { 
                ...data, 
                value: typeof type === 'number' ? parseInt(e.target.value) : e.target.value 
            }
        })
        e.target.blur()
    }
    return <select value={value}
        onChange={handleChange}
        style={{
            backgroundImage: `url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' height='24' viewBox='0 0 24 24' width='24' fill='${theme.getText('primary').hex().replace('#','%23')}'><path d='M0 0h24v24H0z' fill='none'/><path d='M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z'/></svg>")`
        }}
    >
        {children}
    </select>
}

// src/lib/components/inputs/Select.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'
    import {ThemeProvider as theme} from '$core/theme/ThemeProvider.svelte'

    // No `className` prop: old declared one but never used it - dropped
    // rather than porting a dead, unused prop.
    let {
        onchange,
        value,
        children,
        style = '',
    }: {
        onchange: (e: Event & {currentTarget: EventTarget & HTMLSelectElement}) => void
        value: string | number | string[] | undefined
        children?: Snippet
        style?: string
    } = $props()

    function handleChange(e: Event & {currentTarget: EventTarget & HTMLSelectElement}) {
        onchange(e)
        e.currentTarget.blur()
    }

    const backgroundImage = $derived(
        `url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' height='24' viewBox='0 0 24 24' width='24' fill='${theme.getText('primary').hex().replace('#', '%23')}'><path d='M0 0h24v24H0z' fill='none'/><path d='M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z'/></svg>")`
    )
</script>

<select onchange={handleChange} {value} class="select" style="background-image:{backgroundImage};{style}">
    {@render children?.()}
</select>

<style>
    .select {
        background-color: var(--primary);
        border-radius: 0.2rem;
        border: none;
        color: var(--primary-text);
        padding: 0.5rem;
    }

    .select:focus {
        outline: none;
    }

    /* :global() because the <option> elements come from the caller via
       {@render children()}, not from this component's own template - Svelte's
       scoped-CSS pruning can't see them and would otherwise drop this rule as
       an "unused selector". */
    .select :global(option:checked) {
        color: var(--accent);
    }
</style>
