// src/components/Inputs/SongActionButton.tsx
import { hasTooltip, Tooltip } from "../Utility/Tooltip"


interface SongActionButtonProps {
    onClick?: () => void
    style?: React.CSSProperties
    tooltip?: string
    ariaLabel?: string
    className?: string
    children: React.ReactNode
}

export function SongActionButton({ onClick, children, style, tooltip, ariaLabel, className }: SongActionButtonProps) {
    return <>
        <button
            className={`song-button ${hasTooltip(tooltip)} ${className ?? ''}`}
            onClick={onClick || (() => { })}
            style={style}
            aria-label={ariaLabel}
        >
            {children}
            {tooltip &&
                <Tooltip>
                    {tooltip}
                </Tooltip>
            }
        </button>
    </>

}

// src/lib/components/inputs/SongActionButton.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'
    import Tooltip from '../utility/Tooltip.svelte'
    import {hasTooltip} from '../utility/tooltip'

    // `.song-button` is global CSS (App.css) - no component-local <style>
    // is needed here.
    let {
        onclick,
        children,
        style = '',
        tooltip,
        ariaLabel,
        className = '',
    }: {
        onclick?: (e: MouseEvent) => void
        style?: string
        tooltip?: string
        ariaLabel?: string
        className?: string
        children: Snippet
    } = $props()
</script>

<button class="song-button {hasTooltip(tooltip)} {className}" {onclick} {style} aria-label={ariaLabel}>
    {@render children()}
    {#if tooltip}
        <Tooltip>
            {tooltip}
        </Tooltip>
    {/if}
</button>
