// src/lib/components/pages/Composer/MultiSwitch.svelte
<script lang="ts" generics="T extends string">
    // No consumers anywhere in this tree (verified) - dead code, not wired up to anything.
    let {
        options,
        selected,
        buttonsClass,
        onSelect,
    }: {
        options: readonly T[]
        selected: T
        buttonsClass?: string
        onSelect: (selected: T) => void
    } = $props()
</script>

{#each options as value, i (i)}
    <button
        style={selected === value ? 'background-color:var(--accent);color:var(--accent-text)' : ''}
        class={buttonsClass}
        onclick={() => onSelect(value)}
    >
        {value}
    </button>
{/each}

// src/components/Composer/MultiSwitch.tsx
import { memo } from "react"

interface MultiSwitchProps<T> {
    options: readonly T[]
    selected: T
    buttonsClass: string
    onSelect: (selected: T) => void
}

const MultiSwitch = <T,>({ options, selected, buttonsClass, onSelect }: MultiSwitchProps<T>) => {
    return <>
        {options.map((value, i) => {
            return <button
                style={selected === value ? { backgroundColor: 'var(--accent)', color: 'var(--accent-text)' } : {}}
                className={buttonsClass}
                onClick={() => onSelect(value)}
                key={i}
            >
                {value}
            </button>
        })}
    </>
}
export default memo(MultiSwitch, (p, n) => {
    return p.options?.length === n.options?.length
        && p.selected === n.selected
        && p.onSelect === n.onSelect
}) as typeof MultiSwitch
