// src/lib/components/pages/Composer/TimelineButton.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'
    import {hasTooltip} from '$cmp/utility/tooltip'
    import Tooltip from '$cmp/utility/Tooltip.svelte'

    interface TimelineButtonProps {
        onclick: () => void
        tooltip?: string
        ariaLabel?: string
        style?: string
        children: Snippet
    }

    let {onclick, children, tooltip, style, ariaLabel}: TimelineButtonProps = $props()
</script>

<button class={['timeline-button', hasTooltip(tooltip)]} {onclick} {style} aria-label={ariaLabel}>
    {@render children()}
    {#if tooltip}
        <Tooltip>
            {tooltip}
        </Tooltip>
    {/if}
</button>

// src/components/Composer/TimelineButton.tsx
import { Tooltip, hasTooltip } from "$cmp/Utility/Tooltip";

interface TimelineButtonProps {
    onClick: () => void;
    tooltip?: string;
    ariaLabel?: string;
    children: React.ReactNode;
    style?: React.CSSProperties;
}

export function TimelineButton({onClick, children, tooltip, style, ariaLabel}:TimelineButtonProps) {
    return <button
        className={`timeline-button ${hasTooltip(tooltip)}`}
        onClick={onClick}
        style={style}
        aria-label={ariaLabel}
    >
        {children}
        {tooltip &&
            <Tooltip>
                {tooltip}
            </Tooltip>
        }
    </button>
}
