// src/pages/blog/posts/midi-transpose.tsx
import {BlogMetadata} from "$cmp/pages/blog/types";
import {BaseBlogPost} from "$cmp/pages/blog/BaseBlogPost";
import {BlogImage} from "$cmp/pages/blog/BlogImage";
import {Header} from "$cmp/shared/header/Header";
import {AppLink} from "$cmp/shared/link/AppLink";
import {BlogLi, BlogOl} from "$cmp/pages/blog/BlogUl";


export const _midiTransposeMetadata: BlogMetadata = {
    title: "🎛️ MIDI music transposition",
    relativeUrl: "midi-transpose",
    image: '/assets/blog/midi-1.webp',
    description: "Use MIDI songs to transpose music into the app sheet",
    createdAt: new Date("2024/03/19"),
}


export default function BlogPage() {
    return <BaseBlogPost metadata={_midiTransposeMetadata}>
        If you want to compose a song but you don't want to start from 0, you can try to find a MIDI file for the
        song
        and use the MIDI transposing tools to convert it into a music sheet.
        <Header  margin={'1rem 0'}>
            Open a MIDI file
        </Header>
        Once you found your MIDI file, visit the <AppLink href={'/composer'}>composer</AppLink> and open the song
        menu.
        <br/>
        <br/>
        Now click the "Create from MIDI/Audio", it will open the MIDI transposition tool, and select your file after
        pressing the
        "Open MIDI/Audio/Video file" button. If you want to import a video or audio file instead, visit the <AppLink href={'/blog/posts/ai-transpose'}> Ai transpose guide </AppLink>.
        <BlogImage src={'/assets/blog/midi-btn.webp'} alt={"MIDI button"}/>
        <Header  margin={'1rem 0'}>
            Transpose a MIDI file
        </Header>
        After having selected the file, you can start changing the import settings to best convert the song to the
        app sheet.
        The MIDI song doesn't perfectly match the music sheet of the app, so you will have to adjust the settings to
        best fit the song.
        <BlogImage src={'/assets/blog/midi-1.webp'} alt={"MIDI import settings"}/>
        <BlogOl>
            <BlogLi>This is the button to press to select the MIDI file.</BlogLi>
            <BlogLi>
                Here you can select the BPM of the imported song, usually a higher value is preferred, as it leads
                to a better
                conversion accuracy. By default it uses 4 times the song's BPM.
            </BlogLi>
            <BlogLi>
                The note offset is the amount by which notes are "pushed" one note up or down, this is useful when
                the original song is in a
                different pitch, or in a scale that doesn't match the music sheet. This is a value that is applied to
                all tracks, they can then be manually overridden.
            </BlogLi>
            <BlogLi>This is the default pitch of the song, it will be applied to all instruments.</BlogLi>
            <BlogLi>The app's keyboard is made up only of non-accidental notes, by selecting this, all the "accidental"
                notes
                will be pushed one note down, to try to "adapt" the notes to the keyboard. This not always sounds good,
                so try to turn it
                on or off to check which is better.</BlogLi>
            <BlogLi>
                This removes all MIDI tracks which have no notes inside of it, for example, the item at number (7) has
                no notes, so it will be ignored.
            </BlogLi>
            <BlogLi>
                This checkbox decides if to include the track in the conversion or not, next to it there is the name of
                the track, the number of notes inside
                of it, and the instrument that it uses.
            </BlogLi>
            <BlogLi>
                Here you can select the name of the instrument that you want to use for this track.
            </BlogLi>
            <BlogLi>
                This opens the setting of the track, where you can see more information, and override the global values.
            </BlogLi>
        </BlogOl>
        <BlogImage src={'/assets/blog/midi-2.webp'} alt={"MIDI track settings"}/>
        <BlogOl>
            <BlogLi>
                With this you can override the note offset that you wrote in the global settings, leave it blank to use the same
                value of the global offset
            </BlogLi>
            <BlogLi>
                When a note goes over the visible notes of the app, with this value you specify how many times the notes should be
                tried to be "scaled down" by one octave (8 notes), this might allow you to fit more notes of a track, and make it sound
                better.
            </BlogLi>
        </BlogOl>
    </BaseBlogPost>
}

// src/routes/blog/posts/midi-transpose/+page.svelte
<script lang="ts">
  import { base } from '$app/paths';
  import BaseBlogPost from '$cmp/blog/BaseBlogPost.svelte';
  import BlogImage from '$cmp/blog/BlogImage.svelte';
  import AppLink from '$cmp/AppLink.svelte';
  import Header from '$cmp/header/Header.svelte';
  import { midiTransposeMetadata } from '$cmp/blog/posts/midi-transpose';
</script>

<BaseBlogPost metadata={midiTransposeMetadata}>
  <p class="blog-p">
    If you want to compose a song but you don't want to start from 0, you can try to find a MIDI
    file for the song and use the MIDI transposing tools to convert it into a music sheet.
  </p>

  <Header margin="1rem 0">Open a MIDI file</Header>
  <p class="blog-p">
    Once you found your MIDI file, visit the <AppLink href="/composer">composer</AppLink> and open the
    song menu.
  </p>
  <!-- QUIRK: this paragraph is deliberately not wrapped in <p class="blog-p"> like every other
         paragraph in this post - reproduced exactly. -->
  Now click the "Create from MIDI/Audio", it will open the MIDI transposition tool, and select your file
  after pressing the "Open MIDI/Audio/Video file" button. If you want to import a video or audio file
  instead, visit the <AppLink href="/blog/posts/video-audio-transpose">
    Audio transpose guide
  </AppLink>.
  <BlogImage src="{base}/assets/blog/midi-btn.webp" alt="MIDI button" />
  <Header margin="1rem 0">Transpose a MIDI file</Header>
  <p class="blog-p">
    After having selected the file, you can start changing the import settings to best convert the
    song to the app sheet. The MIDI song doesn't perfectly match the music sheet of the app, so you
    will have to adjust the settings to best fit the song.
  </p>

  <BlogImage src="{base}/assets/blog/midi-1.webp" alt="MIDI import settings" />
  <ol class="blog-ol">
    <li>This is the button to press to select the MIDI file.</li>
    <li>
      Here you can select the BPM of the imported song, usually a higher value is preferred, as it
      leads to a better conversion accuracy. By default it uses 4 times the song's BPM.
    </li>
    <li>
      The note offset is the amount by which notes are "pushed" one note up or down, this is useful
      when the original song is in a different pitch, or in a scale that doesn't match the music
      sheet. This is a value that is applied to all tracks, they can then be manually overridden.
    </li>
    <li>This is the default pitch of the song, it will be applied to all instruments.</li>
    <li>
      The app's keyboard is made up only of non-accidental notes, by selecting this, all the
      "accidental" notes will be pushed one note down, to try to "adapt" the notes to the keyboard.
      This not always sounds good, so try to turn it on or off to check which is better.
    </li>
    <li>
      This removes all MIDI tracks which have no notes inside of it, for example, the item at number
      (7) has no notes, so it will be ignored.
    </li>
    <li>
      This checkbox decides if to include the track in the conversion or not, next to it there is
      the name of the track, the number of notes inside of it, and the instrument that it uses.
    </li>
    <li>Here you can select the name of the instrument that you want to use for this track.</li>
    <li>
      This opens the setting of the track, where you can see more information, and override the
      global values.
    </li>
  </ol>
  <BlogImage src="{base}/assets/blog/midi-2.webp" alt="MIDI track settings" />
  <ol class="blog-ol">
    <li>
      With this you can override the note offset that you wrote in the global settings, leave it
      blank to use the same value of the global offset
    </li>
    <li>
      When a note goes over the visible notes of the app, with this value you specify how many times
      the notes should be tried to be "scaled down" by one octave (8 notes), this might allow you to
      fit more notes of a track, and make it sound better.
    </li>
  </ol>
</BaseBlogPost>
