// src/lib/components/i18n/LanguageSelector.svelte
<script lang="ts">
    import {AVAILABLE_LANGUAGES, setI18nLanguage, i18n, type AppLanguage} from '$i18n/i18n'
    import {t, language} from '$i18n/binding.svelte'
    import {capitalize} from '$core/utils/Utilities'
    import {LANG_PREFERENCE_KEY_NAME} from '$core/legacyConfig'
    import {logger} from '$stores/LoggerStore.svelte'

    // All three props below are optional: a bare `<LanguageSelector/>` is a
    // fully self-contained selector (AVAILABLE_LANGUAGES, the current i18n
    // language, and a pill-feedback onChange), but a caller can override any
    // of languages/currentLanguage/onChange to fully control it instead.
    const flagsMap: Record<AppLanguage, string> = {
        en: '🇬🇧',
        zh: '🇨🇳',
        'zh-HK': '🇭🇰',
        'zh-TW': '🇹🇼',
        id: '🇮🇩',
        pt: '🇧🇷',
        ru: '🇷🇺',
        tr: '🇹🇷',
        ja: '🇯🇵',
        ko: '🇰🇷',
    }

    const namesMap: Record<AppLanguage, string> = {
        en: 'English',
        zh: '中文',
        'zh-HK': '中文（香港）',
        'zh-TW': '中文（台灣）',
        id: 'Indonesia',
        pt: 'Brasileiro',
        ru: 'русский',
        tr: 'Türkçe',
        ja: '日本語',
        ko: '한국어',
    }

    function getNameOfLocale(locale: AppLanguage): string {
        // some browsers don't support Intl.DisplayNames
        try {
            if (Intl?.DisplayNames) {
                const nameGenerator = new Intl.DisplayNames(locale, {type: 'language'})
                return nameGenerator.of(locale) ?? namesMap[locale]
            }
        } catch (e) {
            console.error(e)
        }
        return namesMap[locale]
    }

    async function defaultOnChange(lang: AppLanguage) {
        logger.showPill(t('logs:changing_language'))
        const success = await setI18nLanguage(i18n, lang)
        logger.hidePill()
        if (!success) {
            logger.error(t('logs:error_changing_language'))
            return
        }
        localStorage.setItem(LANG_PREFERENCE_KEY_NAME, lang)
    }

    let {
        languages = AVAILABLE_LANGUAGES,
        currentLanguage,
        onChange = defaultOnChange,
        style = '',
        className = '',
    }: {
        languages?: readonly AppLanguage[]
        currentLanguage?: string
        onChange?: (language: AppLanguage) => void
        style?: string
        className?: string
    } = $props()

    // `language()` (not raw `i18n.language`) so this stays reactive to
    // language changes made elsewhere when no `currentLanguage` override is
    // passed.
    const resolvedCurrentLanguage = $derived(currentLanguage ?? language())

    function handleChange(e: Event) {
        onChange((e.target as HTMLSelectElement).value as AppLanguage)
    }
</script>

<select
    value={resolvedCurrentLanguage}
    onchange={handleChange}
    class="i18n-selector {className}"
    style={style}
>
    {#each languages as lang (lang)}
        <option value={lang}>{flagsMap[lang]} {capitalize(getNameOfLocale(lang))}</option>
    {/each}
</select>

<style>
    .i18n-selector {
        padding: 0.5rem;
        gap: 0.2rem;
        display: flex;
        max-width: 8rem;
        padding-right: 1.2rem;
        border-radius: 0.4rem;
        min-width: unset;
        background-color: var(--primary);
        align-items: center;
        appearance: none;
        -webkit-appearance: none;
        border: none;
        color: var(--primary-text);
    }
</style>

// src/components/shared/i18n/LanguageSelector.tsx
import {Stylable} from "$lib/utils/UtilTypes";
import s from './i18n.module.scss'
import {capitalize} from "$lib/utils/Utilities";
import {LANG_PREFERENCE_KEY_NAME} from "$config";
import {useTranslation} from "react-i18next";
import {AppLanguage, AVAILABLE_LANGUAGES, setI18nLanguage} from '$i18n/i18n'
import {logger} from "$stores/LoggerStore";

interface LanguageSelector extends Stylable {
    languages: readonly AppLanguage[]
    currentLanguage: string
    onChange: (language: AppLanguage) => void
}


const flagsMap = {
    'en': '🇬🇧',
    //'it': '🇮🇹',
    'zh': '🇨🇳',
    "id": '🇮🇩',
    'pt': '🇧🇷',
    'ru': '🇷🇺',
    'tr': '🇹🇷'
} satisfies Record<AppLanguage, string>
const namesMap = {
    'en': 'English',
    //'it': 'Italian',
    'zh': '中文',
    "id": 'Indonesia',
    'pt': 'Brasileiro',
    'ru': 'русский',
    'tr': 'Türkçe'
} satisfies Record<AppLanguage, string>

function getNameOfLocale(locale: AppLanguage) {
    // some browsers don't support Intl.DisplayNames
    try {
        if (Intl?.DisplayNames) {
            const nameGenerator = new Intl.DisplayNames(locale, {type: 'language'});
            return nameGenerator.of(locale) ?? namesMap[locale]
        }
    } catch (e) {}
    return namesMap[locale]
}

export function LanguageSelector({languages, currentLanguage, onChange, style, className}: LanguageSelector) {
    return <>
        <select
            value={currentLanguage}
            onChange={(e) => onChange(e.target.value as AppLanguage)}
            className={`${s['i18n-selector']}`}
        >
            {languages.map(language => {
                    const displayName = getNameOfLocale(language)
                    return <option
                        key={language}
                        value={language}
                        suppressHydrationWarning
                    >
                        {flagsMap[language]} {capitalize(displayName)}
                    </option>
                }
            )}
        </select>
    </>
}

export function DefaultLanguageSelector() {
    const {i18n, t} = useTranslation(['logs'])
    return <LanguageSelector
        languages={AVAILABLE_LANGUAGES}
        currentLanguage={i18n.language}
        onChange={async (lang) => {
            logger.showPill(t('changing_language'))
            const success = await setI18nLanguage(i18n, lang)
            logger.hidePill()
            if (!success) {
                logger.error(t('error_changing_language'))
                return
            }
            localStorage.setItem(LANG_PREFERENCE_KEY_NAME, lang)
        }}
    />
}
