// src/lib/components/shell/DefaultPage.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'
    import SimpleMenu from './SimpleMenu.svelte'

    // Deliberately does NOT render AppBackground: each page wires its own
    // directly, not this shared chrome.
    let {
        excludeMenu = false,
        children,
        menu,
        className = '',
        style = '',
        contentStyle = '',
        cropped = true,
    }: {
        excludeMenu?: boolean
        children?: Snippet
        menu?: Snippet
        className?: string
        style?: string
        contentStyle?: string
        cropped?: boolean
    } = $props()

    const hasMenu = $derived(Boolean(menu) || !excludeMenu)
    // padding:0 comes first so a caller's own `style` (appended after) can
    // still override it.
    const pageStyle = $derived(cropped ? style : `padding:0;${style}`)
</script>

<div
    class="default-page {className}"
    style="--left-mobile-padding:{hasMenu ? '5rem' : '1rem'};--right-mobile-padding:{hasMenu ? '1.4rem' : '1rem'};{pageStyle}"
>
    {#if menu}
        {@render menu()}
    {:else if !excludeMenu}
        <SimpleMenu/>
    {/if}
    <main class="default-content appear-on-mount" style={contentStyle}>
        {@render children?.()}
    </main>
</div>

// src/components/shared/pagesLayout/DefaultPage.tsx
import {SimpleMenu} from "./SimpleMenu"
import {CSSProperties, ReactNode} from "react";

interface PageProps {
    excludeMenu?: boolean
    children: ReactNode
    menu?: ReactNode
    className?: string
    style?: CSSProperties
    contentStyle?: CSSProperties
    cropped?: boolean
}

export function DefaultPage({excludeMenu = false, children, className = "", style, menu, cropped = true, contentStyle}: PageProps) {
    const pageStyle = !cropped ? {...style, padding: 0} : style
    const hasMenu = menu || !excludeMenu
    return <div
        className={"default-page " + className}
        style={{
            '--left-mobile-padding': hasMenu ? '5rem' : '1rem',
            '--right-mobile-padding': hasMenu ? '1.4rem' : '1rem',
            ...pageStyle
        } as CSSProperties}
    >
        {menu
            ? menu
            : (!excludeMenu && <SimpleMenu/>)
        }
        <main
            className="default-content appear-on-mount"
            style={contentStyle}
        >
            {children}
        </main>
    </div>
}
