// src/components/Player/PlayerKeyboard.tsx
import {Component} from 'react'
import {APP_NAME, SPEED_CHANGERS, Pitch, NoteNameType} from "$config"
import Note from '$cmp/Player/PlayerNote'
import {playerStore} from '$stores/PlayerStore'
import {Array2d, delay, clamp, groupArrayEvery} from "$lib/Utilities"
import Analytics from '$lib/Stats';
import {playerControlsStore} from '$stores/PlayerControlsStore'
import {ApproachingNote, RecordedNote} from '$lib/Songs/SongClasses'
import type {ObservableNote} from '$lib/Instrument'
import type Instrument from '$lib/Instrument'
import type {Timer} from '$types/GeneralTypes'
import {Chunk, RecordedSong} from '$lib/Songs/RecordedSong'
import {MIDIEvent, MIDIProvider} from '$lib/Providers/MIDIProvider'
import {NoteLayer} from '$lib/Layer'
import {subscribeObeservableObject, subscribeObservableArray} from '$lib/Hooks/useObservable'
import {ShortcutListener, createKeyboardListener, createShortcutListener} from '$/stores/KeybindsStore'

interface KeyboardPlayerProps {
    data: {
        isLoading: boolean
        instrument: Instrument
        pitch: Pitch
        keyboardSize: number
        noteNameType: NoteNameType
        hasSong: boolean
        hasAnimation: boolean
        approachRate: number
        keyboardYPosition: number
        speedChanger: typeof SPEED_CHANGERS[number]
    }
    functions: {
        playSound: (index: number, layer?: NoteLayer) => void
        setHasSong: (override: boolean) => void
    }
}

interface KeyboardPlayerState {
    playTimestamp: number
    songToPractice: Chunk[]
    approachingNotes: ApproachingNote[][]
    keyboard: ObservableNote[]
}

export default class KeyboardPlayer extends Component<KeyboardPlayerProps, KeyboardPlayerState> {
    state: KeyboardPlayerState
    approachRate: number = 1500
    approachingNotesList: ApproachingNote[] = []
    nextChunkDelay: number = 0
    tickTime: number = 50
    tickInterval: number = 0
    mounted: boolean
    songTimestamp = 0
    cleanup: (() => void)[] = []
    timeouts: Timer[] = []
    debouncedStateUpdate: Timer = 0

    constructor(props: KeyboardPlayerProps) {
        super(props)
        this.state = {
            playTimestamp: Date.now(),
            songToPractice: [],
            approachingNotes: Array2d.from(APP_NAME === 'Sky' ? 15 : 21),
            keyboard: playerStore.keyboard
        }
        this.mounted = true
    }

    componentDidMount() {
        this.tickInterval = setInterval(this.tick, this.tickTime) as unknown as number
        const disposeShortcuts = createShortcutListener("player", "player_keyboard", ({shortcut}) => {
            const {name} = shortcut
            if (name === "restart") {
                if (!this.props.data.hasSong) return
                if (['practice', 'play', 'approaching'].includes(playerStore.eventType)) {
                    this.restartSong(0)
                }
            }
            if (name === "stop") {
                if (this.props.data.hasSong) this.stopAndClear()
            }
        })
        const disposeKeyboard = createKeyboardListener("player_keyboard_keys", this.handleKeyboard)
        this.cleanup.push(disposeShortcuts, disposeKeyboard)
        this.cleanup.push(subscribeObeservableObject(playerStore.state, async () => {
            //this is because mobx calls for each prop changed while i want to batch it and execute all at once
            if (this.debouncedStateUpdate) clearTimeout(this.debouncedStateUpdate)
            this.debouncedStateUpdate = setTimeout(async () => {
                const state = playerStore.state
                const song = playerStore.song
                const type = playerStore.eventType
                await this.stopSong()
                if (!this.mounted) return
                if (type === 'stop') {
                    this.props.functions.setHasSong(false)
                } else {
                    if (!song) return
                    const lostReference = song.isComposed
                        ? song.toRecordedSong().clone()
                        : song.clone()

                    lostReference.timestamp = Date.now()
                    const end = state.end || lostReference?.notes?.length || 0
                    if (type === 'play') {
                        this.playSong(lostReference, state.start, end)
                    }
                    if (type === 'practice') {
                        this.practiceSong(lostReference, state.start, end)
                    }
                    if (type === 'approaching') {
                        this.approachingSong(lostReference, state.start, end)
                    }
                    this.props.functions.setHasSong(true)
                    Analytics.songEvent({type})
                    playerControlsStore.setState({
                        size: lostReference?.notes?.length || 1,
                        position: state.start,
                        end,
                        current: state.start
                    })
                }
            }, 4)
        }))
        MIDIProvider.addListener(this.handleMidi)
        this.cleanup.push(() => MIDIProvider.removeListener(this.handleMidi))
        this.cleanup.push(subscribeObservableArray(playerStore.keyboard, () => {
            this.setState({keyboard: playerStore.keyboard})
        }))
    }

    componentWillUnmount() {
        this.cleanup.forEach(d => d())
        this.songTimestamp = 0
        playerStore.resetSong()
        this.mounted = false
        clearInterval(this.tickInterval)
    }

    handleMidi = ([eventType, note, velocity]: MIDIEvent) => {
        if (!this.mounted) return
        const instrument = this.props.data.instrument
        if (MIDIProvider.isDown(eventType) && velocity !== 0) {
            const keyboardNotes = MIDIProvider.getNotesOfMIDIevent(note)
            keyboardNotes.forEach(keyboardNote => {
                this.handleClick(instrument.notes[keyboardNote.index])
            })
        }
    }
    handleKeyboard: ShortcutListener<"keyboard"> = async ({event, shortcut}) => {
        if (event.repeat) return
        if (!event.shiftKey) {
            const note = this.props.data.instrument.getNoteFromCode(shortcut.name)
            if (note !== null) this.handleClick(note)
        }
    }
    approachingSong = async (song: RecordedSong, start = 0, end?: number) => {
        end = end ? end : song.notes.length
        const {speedChanger} = this.props.data
        const notes = []
        this.approachRate = this.props.data.approachRate || 1500
        const startDelay = this.approachRate
        const startOffset = song.notes[start] !== undefined ? song.notes[start].time : 0
        for (let i = start; i < end && i < song.notes.length; i++) {
            const note = song.notes[i]
            const obj = new ApproachingNote({
                time: Math.floor((note.time - startOffset) / speedChanger.value + startDelay),
                index: note.index
            })
            notes.push(obj)
        }
        playerControlsStore.setSong(song)
        playerControlsStore.clearPages()
        playerControlsStore.resetScore()
        this.setState({
            approachingNotes: Array2d.from(APP_NAME === 'Sky' ? 15 : 21),
        })
        this.approachingNotesList = notes
    }

    tick = () => {
        if (!this.props.data.hasSong) return
        const {approachingNotes} = this.state
        const {speedChanger} = this.props.data
        const stateNotes = approachingNotes
        const notes = this.approachingNotesList
        notes.forEach(note => {
            note.time -= this.tickTime
        })
        let hasChanges = false
        let removed = 0
        for (let i = 0; i < notes.length; i++) {
            if (notes[i].time < this.approachRate) {
                const newNote = new ApproachingNote({
                    time: this.approachRate,
                    index: notes[i].index,
                    id: Math.floor(Math.random() * 10000)
                })
                stateNotes[notes[i].index].push(newNote)
                notes.splice(i, 1)
                i--
                hasChanges = true
            } else {
                break
            }
        }
        stateNotes.forEach(approachingNotes => {
            for (let i = 0; i < approachingNotes.length; i++) {
                const note = approachingNotes[i]
                note.time -= this.tickTime
                if (note.clicked) {
                    if (note.time < this.approachRate / 3) {
                        playerControlsStore.increaseScore(true, speedChanger.value)
                    } else {
                        playerControlsStore.increaseScore(false)
                    }
                    note.time = -1 //so that it can be removed after
                }
                if (note.time < 0) {
                    if (!note.clicked) {
                        playerControlsStore.increaseScore(false)
                    }
                    approachingNotes.splice(i, 1)
                    i--
                    hasChanges = true
                    removed++
                }
            }
        })
        if (!hasChanges) return
        playerControlsStore.setCurrent(playerControlsStore.current + removed)
        this.setState({
            approachingNotes: stateNotes.map(arr => arr.slice()), //removes ref
        })
    }

    playSong = async (song: RecordedSong, start = 0, end?: number) => {
        end = end ? end : song.notes.length
        this.songTimestamp = song.timestamp
        const {keyboard} = this.state
        const notes = this.applySpeedChange(song.notes).slice(start, end)
        const mergedNotes = RecordedSong.mergeNotesIntoChunks(notes.map(n => n.clone()))
        playerControlsStore.setPages(groupArrayEvery(mergedNotes, 10))
        await delay(200) //add small start offset
        const startOffset = notes[0].time
        let previous = startOffset
        let delayOffset = 0
        let startTime = Date.now()
        let chunkPlayedNotes = 0
        for (let i = 0; i < notes.length; i++) {
            const delayTime = notes[i].time - previous
            previous = notes[i].time
            if (delayTime > 16) await delay(delayTime + delayOffset)
            if (!this.mounted || this.songTimestamp !== song.timestamp) return
            this.handleClick(keyboard[notes[i].index], notes[i].layer)
            if (chunkPlayedNotes >= (playerControlsStore.currentChunk?.notes.length ?? 0)) {
                chunkPlayedNotes = 1
                playerControlsStore.incrementChunkPositionAndSetCurrent(start + i + 1)
            } else {
                chunkPlayedNotes++
                playerControlsStore.setCurrent(start + i + 1)
            }
            delayOffset = startTime + previous - startOffset - Date.now()
        }
    }
    applySpeedChange = (notes: RecordedNote[]) => {
        const {speedChanger} = this.props.data
        return notes.map(note => {
            note.time = note.time / speedChanger.value
            return note
        })
    }

    practiceSong = (song: RecordedSong, start = 0, end?: number) => {
        //TODO move this to the song class
        end = end ? end : song.notes.length
        const {keyboard} = this.state
        const notes = this.applySpeedChange(song.notes).slice(start, end)
        const chunks = RecordedSong.mergeNotesIntoChunks(notes.map(n => n.clone()))
        if (chunks.length === 0) return
        this.nextChunkDelay = 0
        const firstChunk = chunks[0]
        firstChunk.notes.forEach(note => {
            playerStore.setNoteState(note.index, {
                status: 'toClick',
                delay: APP_NAME === 'Genshin' ? 100 : 200
            })
        })
        const secondChunk = chunks[1]
        secondChunk?.notes.forEach(note => {
            const keyboardNote = keyboard[note.index]
            if (keyboardNote.status === 'toClick') return keyboardNote.setStatus('toClickAndNext')
            keyboardNote.setStatus('toClickNext')
        })
        this.props.functions.setHasSong(true)
        playerControlsStore.setPages(groupArrayEvery(chunks, 10))
        this.setState({
            songToPractice: chunks
        })
    }

    restartSong = async (override?: number) => {
        await this.stopSong()
        if (!this.mounted) return
        playerStore.restartSong((typeof override === 'number') ? override : playerControlsStore.position, playerControlsStore.end)
    }
    stopSong = (): Promise<void> => {
        this.songTimestamp = 0
        return new Promise(res => {
            playerStore.resetKeyboardLayout()
            this.approachingNotesList = []
            this.setState({
                songToPractice: [],
                approachingNotes: Array2d.from(APP_NAME === 'Sky' ? 15 : 21)
            }, res)
            this.props.functions.setHasSong(false)
        })
    }

    stopAndClear = () => {
        this.stopSong()
        playerStore.resetSong()
    }

    handleApproachClick = (note: ObservableNote) => {
        const {approachingNotes} = this.state
        const approachingNote = approachingNotes[note.index][0]
        if (approachingNote) {
            approachingNote.clicked = true
            if (approachingNote.time < this.approachRate / 3) return "approach-correct"
        }
        return "approach-wrong"
    }
    handlePracticeClick = (note: ObservableNote) => {
        const {keyboard, songToPractice} = this.state
        if (songToPractice.length > 0) {
            const clickedNoteIndex = songToPractice[0]?.notes.findIndex(e => e.index === note.index)
            if (clickedNoteIndex !== -1) {
                songToPractice[0].notes.splice(clickedNoteIndex, 1)
                if (songToPractice[0].notes.length === 0) {
                    songToPractice.shift()
                    playerControlsStore.incrementChunkPositionAndSetCurrent()
                }
                if (songToPractice.length > 0) {
                    const nextChunk = songToPractice[0]
                    const nextNextChunk = songToPractice[1]
                    nextChunk.notes.forEach(note => {
                        playerStore.setNoteState(note.index, {
                            status: 'toClick',
                            delay: nextChunk.delay
                        })
                    })
                    if (nextNextChunk) {
                        nextNextChunk?.notes.forEach(note => {
                            const keyboardNote = keyboard[note.index]
                            if (keyboardNote.status === 'toClick') return keyboardNote.setStatus('toClickAndNext')
                            keyboardNote.setStatus('toClickNext')
                        })
                    }
                }
                playerControlsStore.incrementCurrent()
                this.setState({songToPractice})
            }
        }
    }
    handleClick = (note: ObservableNote, layers?: NoteLayer) => {
        const {keyboard} = this.state
        const hasAnimation = this.props.data.hasAnimation
        if (!note) return
        const prevStatus = keyboard[note.index].status
        playerStore.setNoteState(note.index, {
            status: 'clicked',
            delay: playerStore.eventType !== 'play'
                ? APP_NAME === 'Genshin' ? 100 : 200
                : 0,
            animationId: (hasAnimation && playerStore.eventType !== 'approaching')
                ? Math.floor(Math.random() * 10000) + Date.now()
                : 0
        })
        this.handlePracticeClick(note)
        this.props.functions.playSound(note.index, layers)
        const status = this.handleApproachClick(note)
        if (playerStore.eventType === 'approaching') {
            playerStore.setNoteState(note.index, {status})
            if (status === 'approach-wrong') playerControlsStore.increaseScore(false)
        }
        //TODO could add this to the player store
        if (this.timeouts[note.index] as number > 0 && playerStore.eventType === 'play') clearTimeout(this.timeouts[note.index])
        this.timeouts[note.index] = setTimeout(() => {
            this.timeouts[note.index] = 0
            if (!['clicked', 'approach-wrong', 'approach-correct'].includes(keyboard[note.index].status)) return
            if (prevStatus === 'toClickNext') return playerStore.setNoteState(note.index, {status: prevStatus})
            playerStore.setNoteState(note.index, {status: ''})
        }, APP_NAME === 'Sky' ? 200 : 100)
    }

    render() {
        const {state, props} = this
        const {data} = props
        const {instrument, noteNameType, pitch} = data
        const {keyboard} = state
        const size = clamp(data.keyboardSize / 100, 0.5, 1.5)
        let keyboardClass = "keyboard" + (playerStore.eventType === 'play' ? " keyboard-playback" : "")
        if (keyboard.length === 15) keyboardClass += " keyboard-5"
        if (keyboard.length === 14) keyboardClass += " keyboard-5"
        if (keyboard.length === 8) keyboardClass += " keyboard-4"
        if (keyboard.length === 6) keyboardClass += " keyboard-3"
        const style = size !== 1 ? {transform: `scale(${size})`} : {}
        return <>
            <div
                className={keyboardClass}
                style={{
                    ...style,
                    zIndex: 2,
                    marginBottom: `${size * 6 + (data.keyboardYPosition / 10)}vh`
                }}
            >
                {data.isLoading
                    ? <div className="loading">Loading...</div>

                    : keyboard.map(note => {
                        return <Note
                            key={note.index}
                            note={note}
                            data={{
                                approachRate: this.approachRate,
                                instrument: instrument.name,
                            }}
                            approachingNotes={state.approachingNotes[note.index]}
                            handleClick={this.handleClick}
                            noteText={instrument.getNoteText(note.index, noteNameType, pitch)}
                        />

                    })
                }
            </div>
        </>
    }
}

// src/lib/components/pages/Player/PlayerKeyboard.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { game } from '$game';
  import {
    SPEED_CHANGERS,
    SUSTAIN_VISUAL_THRESHOLD_MS,
    type NoteNameType,
    type Pitch,
  } from '$core/legacyConfig';
  import PlayerNote from './PlayerNote.svelte';
  import { playerStore } from '$stores/PlayerStore.svelte';
  import { playerControlsStore } from '$stores/PlayerControlsStore.svelte';
  import { Array2d, clamp, delay, groupArrayEvery, type Timer } from '$core/utils/Utilities';
  import Analytics from '$core/Analytics';
  import { ApproachingNote, type RecordedNote } from '$core/Songs/SongClasses';
  import { displayButtonForId } from '$core/Songs/noteIds';
  import type { Instrument, ObservableNote } from '$lib/audio/Instrument.svelte';
  import { RecordedSong, type Chunk } from '$core/Songs/RecordedSong';
  import { MIDIProvider, type MIDIEvent } from '$lib/providers/MIDIProvider';
  import {
    createKeyboardListener,
    createShortcutListener,
    type ShortcutListener,
  } from '$stores/KeybindsStore.svelte';
  import { t } from '$i18n/binding.svelte';
  import { Song } from '$core/Songs/Song';

  let {
    data,
    functions,
  }: {
    data: {
      isLoading: boolean;
      instrument: Instrument;
      pitch: Pitch;
      keyboardSize: number;
      noteNameType: NoteNameType;
      hasSong: boolean;
      hasAnimation: boolean;
      approachRate: number;
      keyboardYPosition: number;
      speedChanger: (typeof SPEED_CHANGERS)[number];
      visualSheetSize: number;
      hideNotesInPracticeMode: boolean;
    };
    functions: {
      playSound: (index: number, songNote?: RecordedNote) => void;
      releaseSound: (index: number) => void;
      releaseAllSounds: () => void;
      setHasSong: (override: boolean) => void;
      onSongFinished: () => void;
    };
  } = $props();

  let approachRate = $state(1500);
  let approachingNotesList: ApproachingNote[] = [];
  // QUIRK: written but never read - dead field, preserved rather than removed.
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  let nextChunkDelay = 0;
  const tickTime = 50;
  let tickInterval: Timer = 0;
  let mounted = true;
  let songTimestamp = 0;
  let cleanup: (() => void)[] = [];
  let timeouts: Timer[] = [];
  let debouncedStateUpdate: Timer = 0;
  let mode: 'play' | 'practice' | 'approaching' | undefined = $state('play');
  let songToPractice: Chunk[] = [];
  let approachingNotes: ApproachingNote[][] = $state(Array2d.from(game.notes.perColumn));
  // QUIRK: written once, never read again - dead field, preserved rather than removed.
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  let playTimestamp = Date.now();

  function setTicker(enabled: boolean) {
    if (enabled) {
      clearInterval(tickInterval);
      tickInterval = setInterval(tick, tickTime);
    } else {
      clearInterval(tickInterval);
    }
  }

  function handleMidi([eventType, note, velocity]: MIDIEvent) {
    if (!mounted) return;
    const instrument = data.instrument;
    //running-status zero-velocity note-on is the classic note-off alias
    const isRelease =
      MIDIProvider.isUp(eventType) || (MIDIProvider.isDown(eventType) && velocity === 0);
    if (isRelease) {
      const keyboardNotes = MIDIProvider.getNotesOfMIDIevent(note);
      keyboardNotes.forEach((keyboardNote) => {
        const observableNote = instrument.notes[keyboardNote.index];
        if (observableNote) handleRelease(observableNote);
      });
      return;
    }
    if (MIDIProvider.isDown(eventType)) {
      const keyboardNotes = MIDIProvider.getNotesOfMIDIevent(note);
      keyboardNotes.forEach((keyboardNote) => {
        handleClick(instrument.notes[keyboardNote.index]);
      });
    }
  }

  const handleKeyboard: ShortcutListener<'keyboard'> = async ({ event, shortcut }) => {
    if (event.repeat) return;
    if (!event.shiftKey) {
      const note = data.instrument.getNoteFromCode(shortcut.name);
      if (note !== null) handleClick(note);
    }
  };

  //release unconditionally (even if shift is down by now) — releasing an unheld button is a no-op
  const handleKeyboardRelease: ShortcutListener<'keyboard'> = ({ shortcut }) => {
    const note = data.instrument.getNoteFromCode(shortcut.name);
    if (note !== null) handleRelease(note);
  };

  async function approachingSong(song: RecordedSong, start = 0, end?: number) {
    mode = 'approaching';
    setTicker(true);
    end = end ? end : song.notes.length;
    const { speedChanger } = data;
    const notes: ApproachingNote[] = [];
    approachRate = data.approachRate || 1500;
    const startDelay = approachRate;
    const startOffset = song.notes[start] !== undefined ? song.notes[start].time : 0;
    for (let i = start; i < end && i < song.notes.length; i++) {
      const note = song.notes[i];
      //stranded/out-of-grid notes can't be practiced — skip (they were unplayable rows before too)
      if (note.displayButton < 0 || note.displayButton >= game.notes.perColumn) continue;
      const obj = new ApproachingNote({
        time: Song.roundTime((note.time - startOffset) / speedChanger.value + startDelay),
        index: note.displayButton,
        duration: note.duration,
      });
      notes.push(obj);
    }
    await delay(2000); //add an initial delay to let the user prepare
    // QUIRK: playerControlsStore.setSong(song) is intentionally left commented out - nothing
    // reads the stored song, kept as-is rather than deleted or reinstated.
    //playerControlsStore.setSong(song)
    playerControlsStore.clearPages();
    playerControlsStore.resetScore();
    approachingNotes = Array2d.from(game.notes.perColumn);
    approachingNotesList = notes;
  }

  function tick() {
    if (!data.hasSong || mode !== 'approaching') return;
    const stateNotes = approachingNotes;
    const notes = approachingNotesList;
    const { speedChanger } = data;
    notes.forEach((note) => {
      note.time -= tickTime;
    });
    let hasChanges = false;
    for (let i = 0; i < notes.length; i++) {
      if (notes[i].time < approachRate) {
        const newNote = new ApproachingNote({
          time: approachRate,
          index: notes[i].index,
          id: Math.floor(Math.random() * 10000),
          duration: notes[i].duration,
        });
        stateNotes[notes[i].index].push(newNote);
        notes.splice(i, 1);
        i--;
        hasChanges = true;
      } else {
        break;
      }
    }
    let removed = 0;
    stateNotes.forEach((approachingNotesRow) => {
      for (let i = 0; i < approachingNotesRow.length; i++) {
        const note = approachingNotesRow[i];
        note.time -= tickTime;
        if (note.clicked) {
          if (note.time < approachRate / 3) {
            playerControlsStore.increaseScore(true, speedChanger.value);
          } else {
            playerControlsStore.increaseScore(false);
          }
          note.time = -1; //so that it can be removed after
        }
        if (note.time < 0) {
          if (!note.clicked) {
            playerControlsStore.increaseScore(false);
          }
          approachingNotesRow.splice(i, 1);
          i--;
          hasChanges = true;
          removed++;
        }
      }
    });
    if (!hasChanges) return;
    if (playerControlsStore.current + removed === playerControlsStore.size) {
      setTicker(false);
      functions.onSongFinished();
    }
    playerControlsStore.setCurrent(playerControlsStore.current + removed);
    approachingNotes = stateNotes.map((arr) => arr.slice());
  }

  function applySpeedChange(notes: RecordedNote[]) {
    const { speedChanger } = data;
    return notes.map((note) => {
      note.time = note.time / speedChanger.value;
      //held lengths scale with playback speed like everything else
      note.duration = note.duration / speedChanger.value;
      return note;
    });
  }

  function handleRelease(note: ObservableNote) {
    if (!note) return;
    functions.releaseSound(note.index);
  }

  async function playSong(song: RecordedSong, start = 0, end?: number) {
    mode = 'play';
    end = end ? end : song.notes.length;
    songTimestamp = song.timestamp;
    const keyboard = playerStore.keyboard;
    const { visualSheetSize } = data;
    const notes = applySpeedChange(song.notes).slice(start, end);
    const mergedNotes = RecordedSong.mergeNotesIntoChunks(notes.map((n) => n.clone()));
    playerControlsStore.setPages(groupArrayEvery(mergedNotes, visualSheetSize));
    await delay(200); //add small start offset
    const startOffset = notes[0].time;
    let previous = startOffset;
    let delayOffset = 0;
    let startTime = Date.now();
    let chunkPlayedNotes = 0;
    for (let i = 0; i < notes.length; i++) {
      const delayTime = notes[i].time - previous;
      previous = notes[i].time;
      if (delayTime > 16) await delay(delayTime + delayOffset);
      if (!mounted || songTimestamp !== song.timestamp) return;
      handleClick(keyboard[notes[i].displayButton], notes[i]);
      if (chunkPlayedNotes >= (playerControlsStore.currentChunk?.notes.length ?? 0)) {
        chunkPlayedNotes = 1;
        playerControlsStore.incrementChunkPositionAndSetCurrent(start + i + 1);
      } else {
        chunkPlayedNotes++;
        playerControlsStore.setCurrent(start + i + 1);
      }
      delayOffset = startTime + previous - startOffset - Date.now();
    }
    functions.onSongFinished();
  }

  function practiceSong(song: RecordedSong, start = 0, end?: number) {
    mode = 'practice';
    //TODO move this to the song class
    end = end ? end : song.notes.length;
    const keyboard = playerStore.keyboard;
    const { visualSheetSize } = data;
    const notes = applySpeedChange(song.notes).slice(start, end);
    const chunks = RecordedSong.mergeNotesIntoChunks(notes.map((n) => n.clone()));
    if (chunks.length === 0) return;
    nextChunkDelay = 0;
    const firstChunk = chunks[0];
    firstChunk.notes.forEach((note) => {
      playerStore.setNoteState(note.displayButton, {
        status: 'toClick',
        delay: game.notes.animationDelayMs,
        holdMs: note.duration >= SUSTAIN_VISUAL_THRESHOLD_MS ? note.duration : 0,
      });
    });
    const secondChunk = chunks[1];
    secondChunk?.notes.forEach((note) => {
      const keyboardNote = keyboard[note.displayButton];
      if (keyboardNote.status === 'toClick') return keyboardNote.setStatus('toClickAndNext');
      keyboardNote.setStatus('toClickNext');
    });
    functions.setHasSong(true);
    playerControlsStore.setPages(groupArrayEvery(chunks, visualSheetSize));
    songToPractice = chunks;
  }

  async function restartSong(override?: number) {
    await stopSong();
    if (!mounted) return;
    playerStore.restartSong(
      typeof override === 'number' ? override : playerControlsStore.position,
      playerControlsStore.end
    );
  }

  async function stopSong(): Promise<void> {
    songTimestamp = 0;
    playerStore.resetKeyboardLayout();
    approachingNotesList = [];
    songToPractice = [];
    approachingNotes = Array2d.from(game.notes.perColumn);
    //stopping playback releases every still-held voice (live and scheduled)
    functions.releaseAllSounds();
    functions.setHasSong(false);
  }

  function stopAndClear() {
    stopSong();
    playerStore.resetSong();
  }

  function handleApproachClick(note: ObservableNote) {
    const approachingNote = approachingNotes[note.index][0];
    if (approachingNote) {
      approachingNote.clicked = true;
      if (approachingNote.time < approachRate / 3) return 'approach-correct';
    }
    return 'approach-wrong';
  }

  function handlePracticeClick(note: ObservableNote) {
    const keyboard = playerStore.keyboard;
    if (songToPractice.length > 0) {
      const clickedNoteIndex = songToPractice[0]?.notes.findIndex(
        (e) => e.displayButton === note.index
      );
      if (clickedNoteIndex !== -1) {
        songToPractice[0].notes.splice(clickedNoteIndex, 1);
        if (songToPractice[0].notes.length === 0) {
          songToPractice.shift();
          playerControlsStore.incrementChunkPositionAndSetCurrent();
        }
        if (songToPractice.length === 0) {
          functions.onSongFinished();
        }
        if (songToPractice.length > 0) {
          const nextChunk = songToPractice[0];
          const nextNextChunk = songToPractice[1];
          nextChunk.notes.forEach((note) => {
            playerStore.setNoteState(note.displayButton, {
              status: 'toClick',
              delay: nextChunk.delay,
              holdMs: note.duration >= SUSTAIN_VISUAL_THRESHOLD_MS ? note.duration : 0,
            });
          });
          if (nextNextChunk) {
            nextNextChunk?.notes.forEach((note) => {
              const keyboardNote = keyboard[note.displayButton];
              if (keyboardNote.status === 'toClick')
                return keyboardNote.setStatus('toClickAndNext');
              keyboardNote.setStatus('toClickNext');
            });
          }
        }
        playerControlsStore.incrementCurrent();
      }
    }
  }

  function handleClick(note: ObservableNote, songNote?: RecordedNote) {
    const keyboard = playerStore.keyboard;
    const hasAnimation = data.hasAnimation;
    if (!note) return;
    const prevStatus = keyboard[note.index].status;
    playerStore.setNoteState(note.index, {
      status: 'clicked',
      delay: playerStore.eventType !== 'play' ? game.notes.animationDelayMs : 0,
      holdMs: 0,
      animationId:
        hasAnimation && playerStore.eventType !== 'approaching'
          ? Math.floor(Math.random() * 10000) + Date.now()
          : 0,
    });
    handlePracticeClick(note);
    functions.playSound(note.index, songNote);
    const status = handleApproachClick(note);
    if (playerStore.eventType === 'approaching') {
      playerStore.setNoteState(note.index, { status });
      if (status === 'approach-wrong') playerControlsStore.increaseScore(false);
    }
    //TODO could add this to the player store
    if ((timeouts[note.index] as number) > 0 && playerStore.eventType === 'play')
      clearTimeout(timeouts[note.index]);
    //held playback notes keep the button lit for their (speed-scaled) duration
    const litDuration = Math.max(game.notes.animationDelayMs, songNote?.duration ?? 0);
    timeouts[note.index] = setTimeout(() => {
      timeouts[note.index] = 0;
      if (!['clicked', 'approach-wrong', 'approach-correct'].includes(keyboard[note.index].status))
        return;
      if (prevStatus === 'toClickNext')
        return playerStore.setNoteState(note.index, { status: prevStatus });
      playerStore.setNoteState(note.index, { status: '' });
    }, litDuration);
  }

  onMount(() => {
    const disposeShortcuts = createShortcutListener('player', 'player_keyboard', ({ shortcut }) => {
      const { name } = shortcut;
      if (name === 'restart') {
        if (!data.hasSong) return;
        if (['practice', 'play', 'approaching'].includes(playerStore.eventType)) {
          restartSong(0);
        }
      }
      if (name === 'stop') {
        if (data.hasSong) stopAndClear();
      }
    });
    const disposeKeyboard = createKeyboardListener('player_keyboard_keys', handleKeyboard, {
      onRelease: handleKeyboardRelease,
    });
    cleanup.push(disposeShortcuts, disposeKeyboard);

    $effect(() => {
      // Reading key/playId here (values otherwise unused) makes this effect rerun on every
      // play/practice/approaching/restartSong/resetSong call, even when the song object is
      // reference-equal.
      void playerStore.state.key;
      void playerStore.state.playId;
      // This debounce isn't just coalescing multiple fires into one - it defers past the
      // current synchronous call stack, so stopSong() and the mode dispatch below always run
      // after whatever triggered the change (e.g. playerStore.play(...)) has fully returned.
      // Removing it changes that ordering.
      if (debouncedStateUpdate) clearTimeout(debouncedStateUpdate);
      debouncedStateUpdate = setTimeout(async () => {
        const state = playerStore.state;
        const song = playerStore.song;
        const type = playerStore.eventType;
        await stopSong();
        if (!mounted) return;
        if (type === 'stop') {
          functions.setHasSong(false);
        } else {
          if (!song) return;
          const lostReference = song.isComposed ? song.toRecordedSong().clone() : song.clone();
          //resolve each note's display button once, from its own track's instrument;
          //stranded notes are dropped — they had no playable/renderable row before either
          const songInstruments = lostReference.instruments;
          lostReference.notes.forEach((n) => {
            n.displayButton = displayButtonForId(songInstruments[n.trackIndex]?.name ?? '', n.id);
          });
          lostReference.notes = lostReference.notes.filter((n) => n.displayButton !== -1);

          lostReference.timestamp = Date.now();
          const end = state.end || lostReference?.notes?.length || 0;
          if (type === 'play') {
            playSong(lostReference, state.start, end);
          }
          if (type === 'practice') {
            practiceSong(lostReference, state.start, end);
          }
          if (type === 'approaching') {
            approachingSong(lostReference, state.start, end);
          }
          functions.setHasSong(true);
          Analytics.songEvent({ type });
          playerControlsStore.setState({
            size: lostReference?.notes?.length || 1,
            position: state.start,
            end,
            current: state.start,
          });
        }
      }, 4);
    });

    MIDIProvider.addListener(handleMidi);
    cleanup.push(() => MIDIProvider.removeListener(handleMidi));

    return () => {
      cleanup.forEach((d) => d());
      songTimestamp = 0;
      playerStore.resetSong();
      mounted = false;
      clearInterval(tickInterval);
    };
  });

  const size = $derived(clamp(data.keyboardSize / 100, 0.5, 1.5));
  const keyboardClass = $derived.by(() => {
    let cls = 'keyboard' + (playerStore.eventType === 'play' ? ' keyboard-playback' : '');
    const len = playerStore.keyboard.length;
    if (len === 15) cls += ' keyboard-5';
    if (len === 14) cls += ' keyboard-5';
    if (len === 8) cls += ' keyboard-4';
    if (len === 6) cls += ' keyboard-3';
    return cls;
  });
  // $derived.by (not bare $derived(expr)) is required: TypeScript narrows mode to its
  // initializer literal ('play') at this point, since no synchronous code reassigns it first -
  // wrapping the expression in an arrow function (like keyboardClass above) forces a fresh,
  // unnarrowed read of mode's declared type.
  const hideNotes = $derived.by(() => data.hideNotesInPracticeMode && mode === 'practice');
  const wrapperStyle = $derived(
    `${size !== 1 ? `transform:scale(${size});` : ''}z-index:2;margin-bottom:${size * 6 + data.keyboardYPosition / 10}vh`
  );
</script>

<div class={keyboardClass} style={wrapperStyle}>
  {#if data.isLoading}
    <div class="loading">{t('common:loading')}...</div>
  {:else}
    {#each playerStore.keyboard as note (note.index)}
      <PlayerNote
        {note}
        data={{ approachRate, instrument: data.instrument.name }}
        hideNote={hideNotes}
        approachingNotes={approachingNotes[note.index]}
        {handleClick}
        {handleRelease}
        noteText={data.instrument.getNoteText(note.index, data.noteNameType, data.pitch)}
      />
    {/each}
  {/if}
</div>
