// src/pages/donate/index.tsx
import paypalImg from '$/assets/images/paypalme.png'
import kofiImg from '$/assets/images/kofi.png'
import {PageMetadata} from '$cmp/shared/Miscellaneous/PageMetadata'
import {DefaultPage} from '$cmp/shared/pagesLayout/DefaultPage'
import Image from 'next/image'
import s from './Donate.module.css'
import {APP_NAME} from '$config'
import {useTranslation} from "react-i18next";
import {useSetPageVisited} from "$cmp/shared/PageVisit/pageVisit";

export default function Donate() {
    useSetPageVisited('donate')
    const { t} = useTranslation(['donate', 'home'])
    return <DefaultPage>
        <PageMetadata text={t('home:donate_name')} description={`Help the development of ${APP_NAME.toLowerCase()} with a donation.`}/>
        <div className={s['donate-text']}>
            {t('donate_message')}
        </div>
        <div className={s['donation-wrapper']}>
            <a href="https://paypal.me/specyDev" target="_blank" className={s.paypal} rel="noreferrer">
                <Image
                    src={paypalImg}
                    alt='paypalme'
                    loading='lazy'
                    style={{height: "3rem", width: "auto"}}
                />
            </a>
            <a href="https://ko-fi.com/specy" target="_blank" className={s.kofi} rel="noreferrer">
                <Image
                    src={kofiImg}
                    alt='kofi'
                    loading='lazy'
                    style={{height: "2rem", width: "auto"}}
                />
            </a>
        </div>
    </DefaultPage>
}

// src/routes/donate/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import DefaultPage from '$cmp/shell/DefaultPage.svelte';
  import PageMetadata from '$cmp/shell/PageMetadata.svelte';
  import { setPageVisited } from '$stores/PageVisitStore.svelte';
  import { t } from '$i18n/binding.svelte';
  import { game } from '$game';
  import kofi from '$lib/assets/images/donate/kofi.png';
  import paypalme from '$lib/assets/images/donate/paypalme.png';

  onMount(() => {
    setPageVisited('donate');
  });
</script>

<DefaultPage>
  <PageMetadata
    text={t('home:donate_name')}
    description={`Help the development of ${game.id} with a donation.`}
  />
  <div class="donate-text">
    {t('donate:donate_message')}
  </div>
  <div class="donation-wrapper">
    <a href="https://paypal.me/specyDev" target="_blank" class="paypal" rel="noreferrer">
      <img src={paypalme} alt="paypalme" loading="lazy" style="height: 3rem; width: auto;" />
    </a>
    <a href="https://ko-fi.com/specy" target="_blank" class="kofi" rel="noreferrer">
      <img src={kofi} alt="kofi" loading="lazy" style="height: 2rem; width: auto;" />
    </a>
  </div>
</DefaultPage>

<style>
  .donate-text {
    margin: 0 1rem;
    line-height: 1.3rem;
  }

  .donation-wrapper {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    width: 100%;
    justify-content: space-around;
    margin-top: 2rem;
  }

  .donation-wrapper a {
    margin-top: 0.5rem;
  }

  .paypal,
  .kofi {
    background-color: #efefef;
    padding-left: 1rem;
    height: 3rem;
    border-radius: 0.8rem;
  }

  .kofi {
    background-color: white;
    padding: 0.5rem 1rem;
  }
</style>
