// src/components/shared/pagesLayout/MenuPanel.tsx
interface MenuPanelProps<T> {
    title?: string,
    current?: T,
    id?: T,
    children: React.ReactNode
}

export default function MenuPanel<T>({title, current, children, id}: MenuPanelProps<T>) {
    return <div className={current === id ? "menu-panel menu-panel-visible" : "menu-panel"}>
        {title &&
            <div className="menu-title">
                {title}
            </div>
        }
        <div className="panel-content-wrapper">
            {children}
        </div>
    </div>
}

// src/lib/components/menu/MenuPanel.svelte
<script lang="ts" generics="T extends string">
    import type {Snippet} from 'svelte'
    import {getMenuContext} from './menuContext'

    let {
        title,
        children,
        id,
    }: {
        title?: string
        children?: Snippet
        id: T
    } = $props()

    const ctx = getMenuContext<T>()
    const isVisible = $derived(ctx.current === id)
</script>

<div class="menu-panel {isVisible ? 'menu-panel-visible' : ''}">
    {#if title}
        <div class="menu-title">{title}</div>
    {/if}
    <div class="panel-content-wrapper">
        {@render children?.()}
    </div>
</div>
