// src/components/shared/Menu/MenuItem.tsx
import {blurEvent} from "$lib/utils/Utilities"
import s from './menu.module.scss'
import {MaybeChildren, Stylable} from "$lib/utils/UtilTypes";
import {useMenuContext} from "$cmp/shared/Menu/MenuContext";


interface MenuItemProps extends Stylable {
    onClick?: () => void
    ariaLabel: string,
    id: string
}

export function MenuItem({className, style, onClick, children, ariaLabel, id}: MaybeChildren<MenuItemProps>) {
    const {current, open, visible, setCurrent, setOpen} = useMenuContext()
    const isActive = current === id && open && visible
    return <button
        className={`${s['menu-item']} ${isActive ? s['menu-item-active'] : ''} ${className}`}
        style={style}
        aria-label={ariaLabel}
        onClick={(e) => {
            blurEvent(e)
            onClick?.()
            setCurrent(id)
            if (isActive) {
                setOpen(false)
            } else {
                setOpen(true)
            }
        }}
    >
        {children}
    </button>
}

interface MenuButtonProps extends Stylable {
    onClick?: () => void
    ariaLabel: string,
}

export function MenuButton({className, style, onClick, children, ariaLabel}: MaybeChildren<MenuButtonProps>) {
    return <button
        className={`${s['menu-item']} ${className}`}
        style={style}
        aria-label={ariaLabel}
        onClick={(e) => {
            blurEvent(e)
            onClick?.()
        }}
    >
        {children}
    </button>
}

// src/lib/components/menu/MenuItem.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'
    import {blurEvent} from '$core/utils/Utilities'
    import {getMenuContext} from './menuContext'

    // Old: src/components/shared/Menu/MenuItem.tsx (MenuItem export only - MenuButton is its own
    // file here, see MenuButton.svelte). `id`/`ariaLabel` unchanged old prop names; `onClick` ->
    // `onclick`, `className` -> `className` prop but rendered as `class`.
    let {
        className = '',
        style = '',
        onclick,
        children,
        ariaLabel,
        id,
    }: {
        className?: string
        style?: string
        onclick?: () => void
        children?: Snippet
        ariaLabel: string
        id: string
    } = $props()

    const ctx = getMenuContext()
    const isActive = $derived(ctx.current === id && ctx.open && ctx.visible)

    function handleClick(e: MouseEvent) {
        blurEvent(e)
        onclick?.()
        ctx.setCurrent(id)
        // old: `if (isActive) { setOpen(false) } else { setOpen(true) }` - collapsed to the
        // equivalent `setOpen(!isActive)` below.
        ctx.setOpen(!isActive)
    }
</script>

<button
    class="menu-item {isActive ? 'menu-item-active' : ''} {className}"
    style={style}
    aria-label={ariaLabel}
    onclick={handleClick}
>
    {@render children?.()}
</button>
