// src/components/Layout/AppBackground.tsx
import { useThemeOther } from "lib/Hooks/useThemeOther"

interface AppBackgroundProps {
    children: React.ReactNode,
    page: 'Composer' | 'Main'
}
export function AppBackground({ children, page }: AppBackgroundProps) {
    const [theme] = useThemeOther()
    return <div 
        className='app bg-image' 
        //@ts-ignore
        style={{ backgroundImage: `url(${theme.getOther('backgroundImage' + page)}` }}>
        {children}
    </div>
}

// src/lib/components/theme/AppBackground.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'
    import {ThemeProvider as theme, type BackgroundProps} from '$core/theme/ThemeProvider.svelte'

    let {page, children}: {page: BackgroundProps, children: Snippet} = $props()

    const backgroundImage = $derived(theme.getOther(`backgroundImage${page}`))
</script>

<div class="app bg-image" style="background-image:url({backgroundImage})">
    {@render children()}
</div>
