// src/pages/blog/posts/easyplay-1s.tsx
import {BlogMetadata} from "$cmp/pages/blog/types";
import {BaseBlogPost, SpecyAuthor} from "$cmp/pages/blog/BaseBlogPost";
import {Header} from "$cmp/shared/header/Header";
import {BlogIframe, BlogLi, BlogLink, BlogP, BlogUl} from "$cmp/pages/blog/BlogUl";
import {BASE_PATH} from "$config";
import {BlogImage} from "$cmp/pages/blog/BlogImage";


export const _easyplay1sMetadata: BlogMetadata = {
    title: "🎹 EASYPLAY 1s",
    tags: ["Product"],
    relativeUrl: "easyplay-1s",
    image: BASE_PATH + '/assets/blog/easyplay.webp',
    description: "The EASYPLAY 1s, the perfect keyboard for Sky Music Nightly",
    createdAt: new Date("2024/04/24"),
    author: SpecyAuthor,
}


export default function Easyplay1sPageBlog() {
    return <BaseBlogPost metadata={_easyplay1sMetadata}>
        <Header>
            What it is
        </Header>

        <BlogP>
            The EASYPLAY 1s is a keyboard that uses the same layout as Sky Music Nightly, and you can use it in the app
            to help you
            to compose songs and to learn them. <BlogLink external href={'https://summertones-1.kckb.me/18287a61'}>You
            can find the keyboard on kickstarter here</BlogLink>.
        </BlogP>
        <BlogLink href={'https://summertones-1.kckb.me/18287a61'}>
            <BlogImage
                src={BASE_PATH + '/assets/blog/easyplay.webp'}
                alt={'Easyplay 1S'}
                height={'15rem'}
            />
        </BlogLink>
        <Header>
            The features
        </Header>
        <BlogP>
            It is a MIDI keyboard which uses the same layout as Sky Music Nightly, the main features are:
        </BlogP>
        <BlogUl>
            <BlogLi>20 instruments, most of which can be sustained</BlogLi>
            <BlogLi>4 octaves of pitch change</BlogLi>
            <BlogLi>Adjustable volume through a speaker and an headphone jack</BlogLi>
            <BlogLi>MIDI support through USB-C</BlogLi>
        </BlogUl>
        <BlogP>
            It's made out of translucent black plastic with replaceable keycaps and rubber pads to prevent slipping.

        </BlogP>
        <Header>
            Demo video
        </Header>
        <BlogIframe src={'https://www.youtube.com/embed/l64Qdm-FpVU?si=NmbU0nVSrLlWTsBh'}/>
        <BlogP>
            If you are interested, <BlogLink external href={'https://summertones-1.kckb.me/18287a61'}>you can find the
            keyboard on kickstarter here</BlogLink>.
        </BlogP>
    </BaseBlogPost>
}

// src/routes/blog/posts/easyplay-1s/+page.svelte
<script lang="ts">
    import BaseBlogPost from '$cmp/blog/BaseBlogPost.svelte'
    import BlogImage from '$cmp/blog/BlogImage.svelte'
    import AppLink from '$cmp/AppLink.svelte'
    import Header from '$cmp/header/Header.svelte'
    import {base} from '$app/paths'
    import {easyplay1sMetadata} from '$cmp/blog/posts/easyplay-1s'

</script>

<BaseBlogPost metadata={easyplay1sMetadata}>
    <Header>
        What it is
    </Header>

    <p class="blog-p">
        The EASYPLAY 1s is a keyboard that uses the same layout as Sky Music Nightly, and you can use it in the app
        to help you
        to compose songs and to learn them. <AppLink target="_blank" href="https://summertones-1.kckb.me/18287a61" className="blog-link">You
        can find the keyboard on kickstarter here</AppLink>.
    </p>
    <!-- QUIRK: this link doesn't get target="_blank" even though it's the exact same external
         kickstarter URL as the two text links above/below, which do. Reproduced exactly - only
         this one link doesn't open in a new tab. -->
    <AppLink href="https://summertones-1.kckb.me/18287a61" className="blog-link">
        <BlogImage
            src="{base}/assets/blog/easyplay.webp"
            alt="Easyplay 1S"
            height="15rem"
        />
    </AppLink>
    <Header>
        The features
    </Header>
    <p class="blog-p">
        It is a MIDI keyboard which uses the same layout as Sky Music Nightly, the main features are:
    </p>
    <ul>
        <li>20 instruments, most of which can be sustained</li>
        <li>4 octaves of pitch change</li>
        <li>Adjustable volume through a speaker and an headphone jack</li>
        <li>MIDI support through USB-C</li>
    </ul>
    <p class="blog-p">
        It's made out of translucent black plastic with replaceable keycaps and rubber pads to prevent slipping.

    </p>
    <Header>
        Demo video
    </Header>
    <!-- old's own BlogIframe never had a title prop at all (BlogUl.tsx / this post's sole call
         site) - a pre-existing accessibility gap, preserved rather than fabricating a title old
         never had. -->
    <!-- svelte-ignore a11y_missing_attribute -->
    <iframe src="https://www.youtube.com/embed/l64Qdm-FpVU?si=NmbU0nVSrLlWTsBh" class="blog-iframe"></iframe>
    <p class="blog-p">
        If you are interested, <AppLink target="_blank" href="https://summertones-1.kckb.me/18287a61" className="blog-link">you can find the
        keyboard on kickstarter here</AppLink>.
    </p>
</BaseBlogPost>
