// src/lib/components/BaseNote.svelte
<script lang="ts" generics="T">
    import {game} from '$game'
    import {ThemeProvider as theme} from '$core/theme/ThemeProvider.svelte'
    import {preventDefault} from '$core/utils/Utilities'
    import type {NoteImage} from '$lib/games/types'
    import GenshinNoteBorder from './GenshinNoteBorder.svelte'
    import SvgNote from './SvgNote.svelte'

    // `theme.get(...)` inside `getTextColor()`'s `$derived` (below) auto-tracks
    // ThemeProvider's rune-backed state, so no manual subscribe/dispose is needed.
    //
    // Two-tier rule (see legacyConfig.ts): this file is UI code, so game-data
    // constants are read from `$game` directly, not `$core/legacyConfig`.
    type BaseNoteData = {
        status: 'clicked' | string
    }

    let {
        data,
        // QUIRK: typed required below but keeps a runtime default - dead under
        // the type system, live if a caller ignores the type and omits it anyway.
        noteText = 'A',
        handleClick,
        noteImage,
        clickClass = '',
        noteClass = '',
        // QUIRK: bindable but no current caller binds to it - kept for API
        // parity, not dead code to prune.
        noteRef = $bindable(),
    }: {
        data: T & BaseNoteData
        clickClass?: string
        noteClass?: string
        noteRef?: HTMLDivElement
        noteText: string
        handleClick: (data: T & BaseNoteData) => void
        noteImage?: NoteImage
    } = $props()

    function parseClass(status: string, clickClass: string) {
        let className = game.notes.cssClasses.note
        switch (status) {
            case 'clicked':
                className += ` click-event ${clickClass}`
                break
            default:
                break
        }
        return className
    }

    function parseBorderColor(status: string) {
        if (status === 'clicked') return 'transparent'
        if (status === 'wrong') return '#d66969'
        if (status === 'right') return '#358a55'
        return game.features.hasNoteFrame ? '#eae5ce' : 'unset'
    }

    function getTextColor() {
        const noteBg = theme.get('note_background')
        if (game.features.hasNoteFrame) {
            if (noteBg.luminosity() > 0.65) {
                return game.themes.baseConfig.text.note
            } else {
                return noteBg.isDark() ? game.themes.baseConfig.text.light : game.themes.baseConfig.text.dark
            }
        } else {
            return noteBg.isDark() ? game.themes.baseConfig.text.light : game.themes.baseConfig.text.dark
        }
    }

    const className = $derived(`${parseClass(data.status, clickClass)} ${noteClass}`)
    const borderColor = $derived(parseBorderColor(data.status))
    const textColor = $derived(getTextColor())
</script>

<button
    onpointerdown={(e) => {
        preventDefault(e)
        handleClick(data)
    }}
    oncontextmenu={preventDefault}
    class="button-hitbox-bigger"
>
    <div bind:this={noteRef} class={className} style="border-color:{borderColor}">
        {#if game.features.hasNoteFrame}
            <GenshinNoteBorder class="genshin-border" fill={borderColor} />
        {/if}
        {#if noteImage}
            <SvgNote
                name={noteImage}
                background={data.status === 'clicked' ? 'var(--accent)' : 'var(--note-background)'}
            />
        {/if}
        <div class={game.notes.cssClasses.noteName} style="color:{textColor}">
            {noteText}
        </div>
    </div>
</button>

// src/components/Miscellaneous/BaseNote.tsx
import { NOTES_CSS_CLASSES, APP_NAME, BASE_THEME_CONFIG } from "$config"
import GenshinNoteBorder from '$cmp/Miscellaneous/GenshinNoteBorder'
import { observe } from "mobx"
import { useEffect, useState } from "react"
import { ThemeProvider } from "$stores/ThemeStore/ThemeProvider"
import SvgNotes, { NoteImage } from "$cmp/SvgNotes"


type BaseNoteData = {
    status: 'clicked' | string
}
interface BaseNoteProps<T>{
    data: T & BaseNoteData
    clickClass?: string
    noteClass?: string
    noteRef?: React.RefObject<HTMLDivElement>
    noteText: string,
    handleClick: (data: T & BaseNoteData) => void,
    noteImage?: NoteImage
}
export default function BaseNote<T>({ data, noteText = 'A', handleClick, noteImage, clickClass = '', noteClass = '', noteRef }: BaseNoteProps<T>) {
    const [textColor, setTextColor] = useState(getTextColor())
    useEffect(() => {
        const dispose = observe(ThemeProvider.state.data, () => {
            setTextColor(getTextColor())
        })
        return dispose
    }, [])
    const className = parseClass(data.status, clickClass) + ` ${noteClass}`
    return <button
        onPointerDown={(e) => {
            e.preventDefault()
            handleClick(data)
        }}
        className="button-hitbox-bigger"
    >
        <div
            ref={noteRef}
            className={className}
            style={{ borderColor: parseBorderColor(data.status) }}
        >
            {APP_NAME === 'Genshin' && <GenshinNoteBorder
                className='genshin-border'
                fill={parseBorderColor(data.status)}
            />}
            {noteImage &&
                <SvgNotes
                    name={noteImage}
                    background={
                        data.status === 'clicked'
                            ? 'var(--accent)'
                            : 'var(--note-background)'
                    }
                />
            }
            <div className={NOTES_CSS_CLASSES.noteName} style={{ color: textColor }}>
                {noteText}
            </div>
        </div>
    </button>
}

function parseClass(status: string, clickClass: string) {
    let className = NOTES_CSS_CLASSES.note
    switch (status) {
        case 'clicked': className += ` click-event ${clickClass}`; break;
        default: break;
    }
    return className
}

function parseBorderColor(status: string) {
    let fill = APP_NAME === "Genshin" ? '#eae5ce' : ''
    if (status === "clicked") fill = "transparent"
    else if (status === 'wrong') fill = "#d66969"
    else if (status === 'right') fill = "#358a55"
    return fill
}

function getTextColor() {
    const noteBg = ThemeProvider.get('note_background')
    if (APP_NAME === 'Genshin') {
        if (noteBg.luminosity() > 0.65) {
            return BASE_THEME_CONFIG.text.note
        } else {
            return noteBg.isDark() ? BASE_THEME_CONFIG.text.light : BASE_THEME_CONFIG.text.dark
        }
    } else {
        return noteBg.isDark() ? BASE_THEME_CONFIG.text.light : BASE_THEME_CONFIG.text.dark
    }
}
