// src/components/pages/Composer/MidiParser/TrackInfo.tsx
import {InstrumentData} from '$lib/Songs/SongClasses'
import {FaArrowDown, FaArrowUp, FaCog} from 'react-icons/fa'
import {CustomTrack} from './index'
import {useCallback, useEffect, useState} from 'react'
import useDebounce from '$lib/Hooks/useDebounce'
import {Select} from '$cmp/shared/Inputs/Select'
import {Theme} from '$stores/ThemeStore/ThemeProvider'
import {hasTooltip, Tooltip} from '$cmp/shared/Utility/Tooltip'
import {NumericalInput} from './Numericalinput'
import {prettyPrintInstrumentName} from '$lib/utils/Utilities'
import {Column} from "$cmp/shared/layout/Column";
import {Row} from "$cmp/shared/layout/Row";
import {useTranslation} from "react-i18next";

interface TrackProps {
    data: CustomTrack
    index: number
    instruments: InstrumentData[]
    onChange: (index: number, data: Partial<CustomTrack>) => void
    theme: Theme
}

export function TrackInfo({data, index, onChange, theme, instruments}: TrackProps) {
    const {t} = useTranslation(['composer', 'common'])
    const [dataShown, setDataShown] = useState(false)
    const background = {backgroundColor: theme.layer('menu_background', 0.15).toString()}
    const [offset, setOffset] = useState(`${data.localOffset ?? ""}`)
    const debouncedOffset = useDebounce<string>(offset, 600)

    useEffect(() => {
        const parsedOffset = parseInt(debouncedOffset)
        const localOffset = Number.isFinite(parsedOffset) ? parsedOffset : null
        setOffset(`${localOffset ?? ""}`)
        onChange(index, {localOffset})
    }, [debouncedOffset, onChange, index]);

    useEffect(() => {
        setOffset(`${data.localOffset ?? ""}`)
    }, [data.localOffset])

    const onMaxScaleChange = useCallback((maxScaling: number) => {
        onChange(index, {maxScaling: Math.max(0, maxScaling)})
    }, [onChange, index])
    return <Column gap={'0.5rem'} className='midi-track-column' style={background}>
        <div className='midi-track-wrapper'>
            <div className='midi-track-center'>
                <input type='checkbox' onChange={() => onChange(index, {selected: !data.selected})}
                       checked={data.selected}/>
                {`${data.name} `}
                (
                {data.track.notes.length},
                {` ${data.track.instrument.family}`}
                )
            </div>
            <div className='midi-track-center'>
                <Select
                    onChange={(event) => onChange(index, {layer: Number(event.target.value)})}
                    value={data.layer}
                    className='midi-select'
                    style={{
                        marginLeft: '0.2rem',
                        paddingRight: '1.5rem'
                    }}
                >
                    {instruments.map((ins, i) =>
                        <option value={i} key={i}>
                            {ins.alias || prettyPrintInstrumentName(ins.name)} - {`Layer ${i + 1}`}
                        </option>
                    )}
                </Select>
                <FaCog
                    size={22}
                    color={dataShown ? 'var(--secondary)': 'var(--primary)'}
                    onClick={() => setDataShown(!dataShown)}
                    cursor='pointer'
                />
            </div>
        </div>
        <Column
            padding={'0.4rem'}
            gap={'0.2rem'}
            style={{
                display: dataShown ? "flex" : "none",
                borderTop: 'solid 0.1rem var(--secondary)'
            }}
        >
            <Row align={'center'} justify={'between'}>
                <div className={hasTooltip(true)}>
                    <Tooltip>
                        {t('midi_parser.local_note_offset_description')}
                    </Tooltip>
                    {t('midi_parser.local_note_offset')}
                </div>
                <Row gap={'0.3rem'}>
                    <button
                        onClick={() => setOffset(`${Number(offset) - 1}`)}
                        className='midi-btn-small'
                    >-
                    </button>
                    <input
                        type='text'
                        value={offset}
                        placeholder='No offset'
                        className='midi-input'
                        style={{width: '4rem'}}
                        onChange={(e) => setOffset(e.target.value)}
                    />
                    <button
                        onClick={() => setOffset(`${Number(offset) + 1}`)}
                        className='midi-btn-small'
                    >+
                    </button>
                </Row>
            </Row>
            <Row align={'center'} justify={'between'}>
                <div className={hasTooltip(true)}>
                    <Tooltip>
                        {t('midi_parser.max_octave_scaling_description')}
                    </Tooltip>
                    {t('midi_parser.max_octave_scaling')}
                </div>
                <NumericalInput
                    value={data.maxScaling}
                    placeholder='No scaling'
                    onChange={onMaxScaleChange}
                />
            </Row>
            <Row align={'center'} justify={'between'}>
                <div>{t('common:instrument')}</div>
                <div>{data.track.instrument.name}</div>
            </Row>
            <Row align={'center'} justify={'between'}>
                <div>{t('midi_parser.number_of_notes')}</div>
                <div>{data.track.notes.length}</div>
            </Row>
            <Row align={'center'} justify={'between'}>
                <div>{t('midi_parser.accidentals')}</div>
                <div>{data.numberOfAccidentals}</div>
            </Row>
            <Row align={'center'} justify={'between'}>
                <div>{t('midi_parser.out_of_range')}({data.outOfRangeBounds.upper + data.outOfRangeBounds.lower})</div>
                <Row style={{width: 'fit-content'}}>
                    <Row style={{marginRight: '0.4rem'}}>
                        <FaArrowUp style={{marginRight: '0.2rem'}}/>
                        {data.outOfRangeBounds.upper}
                    </Row>
                    <Row>
                        <FaArrowDown style={{marginRight: '0.2rem'}}/>
                        {data.outOfRangeBounds.lower}
                    </Row>
                </Row>
            </Row>
        </Column>
    </Column>
}

// src/lib/components/pages/Composer/MidiParser/TrackInfo.svelte
<script lang="ts">
  import type { CustomTrack } from './MidiParser.svelte';
  import type { InstrumentData } from '$core/Songs/SongClasses';
  import { ThemeProvider } from '$core/theme/ThemeProvider.svelte';
  import { prettyPrintInstrumentName } from '$core/utils/Utilities';
  import { t } from '$i18n/binding.svelte';
  import Row from '$cmp/layout/Row.svelte';
  import Column from '$cmp/layout/Column.svelte';
  import Select from '$cmp/inputs/Select.svelte';
  import Tooltip from '$cmp/utility/Tooltip.svelte';
  import { hasTooltip } from '$cmp/utility/tooltip';
  import NumericalInput from './NumericalInput.svelte';
  import MidiStatsTable from './MidiStatsTable.svelte';

  let {
    data,
    index,
    onChange,
    instruments,
  }: {
    data: CustomTrack;
    index: number;
    instruments: InstrumentData[];
    onChange: (index: number, data: Partial<CustomTrack>) => void;
  } = $props();

  let dataShown = $state(false);
  const background = $derived(
    `background-color:${ThemeProvider.layer('menu_background', 0.15).toString()}`
  );

  function onLocalOffsetChange(localOffset: number | null) {
    onChange(index, { localOffset });
  }

  function onMaxScaleChange(maxScaling: number) {
    onChange(index, { maxScaling: Math.max(0, maxScaling) });
  }
</script>

<Column class={['midi-track-column', dataShown && 'midi-track-open']}>
  <div class="midi-track-wrapper" style={background}>
    <div class="midi-track-center">
      <input
        type="checkbox"
        onchange={() => onChange(index, { selected: !data.selected })}
        checked={data.selected}
      />
      {`${data.name} (${data.track.notes.length}, ${data.track.instrument.family})`}
    </div>
    <div class="midi-track-center">
      <Select
        onchange={(e) => onChange(index, { layer: Number(e.currentTarget.value) })}
        value={data.layer}
        style="margin-left:0.2rem;padding-right:1.5rem"
      >
        {#each instruments as ins, i (i)}
          <option value={i}
            >{ins.alias || prettyPrintInstrumentName(ins.name)} - Layer {i + 1}</option
          >
        {/each}
      </Select>
      <!-- This svg is a mouse-only click target (no keyboard equivalent) - an accepted
                 a11y gap, not wrapped in a button. -->
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <svg
        stroke="currentColor"
        fill="currentColor"
        stroke-width="0"
        viewBox="0 0 512 512"
        height="22"
        width="22"
        xmlns="http://www.w3.org/2000/svg"
        style="color:{dataShown ? 'var(--secondary)' : 'var(--primary)'}"
        cursor="pointer"
        onclick={() => (dataShown = !dataShown)}
        ><path
          d="M487.4 315.7l-42.6-24.6c4.3-23.2 4.3-47 0-70.2l42.6-24.6c4.9-2.8 7.1-8.6 5.5-14-11.1-35.6-30-67.8-54.7-94.6-3.8-4.1-10-5.1-14.8-2.3L380.8 110c-17.9-15.4-38.5-27.3-60.8-35.1V25.8c0-5.6-3.9-10.5-9.4-11.7-36.7-8.2-74.3-7.8-109.2 0-5.5 1.2-9.4 6.1-9.4 11.7V75c-22.2 7.9-42.8 19.8-60.8 35.1L88.7 85.5c-4.9-2.8-11-1.9-14.8 2.3-24.7 26.7-43.6 58.9-54.7 94.6-1.7 5.4.6 11.2 5.5 14L67.3 221c-4.3 23.2-4.3 47 0 70.2l-42.6 24.6c-4.9 2.8-7.1 8.6-5.5 14 11.1 35.6 30 67.8 54.7 94.6 3.8 4.1 10 5.1 14.8 2.3l42.6-24.6c17.9 15.4 38.5 27.3 60.8 35.1v49.2c0 5.6 3.9 10.5 9.4 11.7 36.7 8.2 74.3 7.8 109.2 0 5.5-1.2 9.4-6.1 9.4-11.7v-49.2c22.2-7.9 42.8-19.8 60.8-35.1l42.6 24.6c4.9 2.8 11 1.9 14.8-2.3 24.7-26.7 43.6-58.9 54.7-94.6 1.5-5.5-.7-11.3-5.6-14.1zM256 336c-44.1 0-80-35.9-80-80s35.9-80 80-80 80 35.9 80 80-35.9 80-80 80z"
        /></svg
      >
    </div>
  </div>
  <Column
    padding="0.4rem"
    gap="0.4rem"
    style="display:{dataShown ? 'flex' : 'none'};border-top:solid 0.1rem var(--secondary)"
  >
    <Row align="center" justify="between">
      <div class={hasTooltip(true)}>
        <Tooltip>
          {t('composer:midi_parser.local_note_offset_description')}
        </Tooltip>
        {t('composer:midi_parser.local_note_offset')}
      </div>
      <NumericalInput
        value={data.localOffset}
        nullable
        placeholder={t('composer:midi_parser.no_offset')}
        delay={600}
        onChange={onLocalOffsetChange}
      />
    </Row>
    <Row align="center" justify="between">
      <div class={hasTooltip(true)}>
        <Tooltip>
          {t('composer:midi_parser.max_octave_scaling_description')}
        </Tooltip>
        {t('composer:midi_parser.max_octave_scaling')}
      </div>
      <NumericalInput
        value={data.maxScaling}
        placeholder={t('composer:midi_parser.no_scaling')}
        onChange={onMaxScaleChange}
      />
    </Row>
    <Row align="center" justify="between">
      <div>{t('common:instrument')}</div>
      <div>{data.track.instrument.name}</div>
    </Row>
    <MidiStatsTable
      notes={data.track.notes.length}
      accidentals={data.numberOfAccidentals}
      outOfRange={data.outOfRangeBounds.upper + data.outOfRangeBounds.lower}
      outOfRangeBounds={data.outOfRangeBounds}
    />
  </Column>
</Column>
