// src/lib/components/pages/VsrgComposer/VsrgTrackSettings.svelte
<script lang="ts">
    import Color from 'color'
    import type {VsrgTrack} from '$core/Songs/VsrgSong'
    import type {Pitch} from '$lib/games/types'
    import {vsrgComposerStore} from '$stores/VsrgComposerStore.svelte'
    import {t} from '$i18n/binding.svelte'
    import Row from '$cmp/layout/Row.svelte'
    import Column from '$cmp/layout/Column.svelte'
    import AppButton from '$cmp/inputs/AppButton.svelte'
    import InstrumentSelect from '$cmp/inputs/InstrumentSelect.svelte'
    import PitchSelect from '$cmp/inputs/PitchSelect.svelte'
    import HelpTooltip from '$cmp/utility/HelpTooltip.svelte'
    import ColorPicker from '$cmp/inputs/ColorPicker.svelte'

    // QUIRK: track's type claims non-optional, but the parent (vsrg.tracks[selectedTrack]) can
    // pass it as undefined for one render right after deleting the selected track - keep the
    // {#if track} guard below despite what the type says.
    let {
        track,
        onSave,
        onDelete,
        onChange,
    }: {
        track: VsrgTrack
        onSave: () => void
        onDelete: () => void
        onChange: (track: VsrgTrack) => void
    } = $props()

    // QUIRK: onChange(track) below always hands back the SAME (mutated in place) VsrgTrack
    // reference the parent already holds - it is not a "new value" signal. The parent re-triggers
    // its own refresh on any call regardless of reference equality; don't add a reference-equality
    // check here or upstream expecting onChange to only fire on a genuine identity change.
    let isColorPickerOpen = $state(false)
</script>

{#snippet faTrashIcon()}
    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 448 512" style="color:var(--red);margin-right:0.3rem" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M432 32H312l-9.4-18.7A24 24 0 0 0 281.1 0H166.8a23.72 23.72 0 0 0-21.4 13.3L136 32H16A16 16 0 0 0 0 48v32a16 16 0 0 0 16 16h416a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16zM53.2 467a48 48 0 0 0 47.9 45h245.8a48 48 0 0 0 47.9-45L416 128H32z"/></svg>
{/snippet}

{#if track}
    <div class="vsrg-floating-settings box-shadow">
        <Row justify="between" align="center">
            {t('vsrg_composer:track_name')}
            <input
                type="text"
                maxlength="50"
                class="input"
                style="width:7.4rem"
                value={track.instrument.alias}
                oninput={(e) => {
                    track.instrument.set({alias: e.currentTarget.value})
                    onChange(track)
                }}
                placeholder={t(`instruments:${track.instrument.name}`)}
            />
        </Row>
        <Row justify="between" align="center" style="margin-top:0.4rem">
            {t('common:instrument')}
            <InstrumentSelect
                style="width:8rem"
                selected={track.instrument.name}
                onChange={(name) => {
                    track.instrument.set({name})
                    onChange(track)
                }}
            />
        </Row>
        <Row justify="between" align="center" style="margin-top:0.4rem">
            {t('common:pitch')}
            <PitchSelect
                style="width:8rem"
                selected={track.instrument.pitch as Pitch}
                onChange={(pitch) => {
                    track.instrument.set({pitch})
                    onChange(track)
                }}
            >
                <option value="">
                    {t('instrument_settings:use_song_pitch')}
                </option>
            </PitchSelect>
        </Row>
        <Row align="center" style="margin-top:1rem">
            {t('instrument_settings:volume')}
            <!-- old redundantly re-declared margin-left here too (a harmless no-op); dropped to
                 satisfy svelte/no-dupe-style-properties (a lint error) - only the color addition
                 below is the real conditional effect. -->
            <span style="margin-left:0.4rem;width:3rem;{track.instrument.volume > 100 ? `color:hsl(0, ${-40 + track.instrument.volume}%, 61%)` : ''}">
                {track.instrument.volume}%
            </span>
            <HelpTooltip buttonStyle="width:1.2rem;height:1.2rem" width={10}>
                {t('instrument_settings:volume_high_warning')}
            </HelpTooltip>
        </Row>
        <Row align="center">
            <input
                type="range"
                style="flex:1"
                min="0"
                max="125"
                value={track.instrument.volume}
                oninput={(e) => {
                    track.instrument.set({volume: parseInt(e.currentTarget.value)})
                    onChange(track)
                }}
            />
        </Row>
        <Column>
            <Row justify="between" align="center">
                {t('common:color')}
                <AppButton
                    onclick={() => isColorPickerOpen = true}
                    ariaLabel="Change color"
                    style="background-color:{track.color};color:{Color(track.color).isDark() ? '#fff' : '#000'}"
                >
                    {t('common:change')}
                </AppButton>
            </Row>
        </Column>
        <Row justify="between" style="margin-top:0.4rem">
            <AppButton className="row-centered" style="padding:0.4rem;width:fit-content" onclick={onDelete}>
                {@render faTrashIcon()}
                {t('common:delete')}
            </AppButton>
            <AppButton onclick={onSave} style="padding:0.4rem;width:fit-content">
                {t('common:ok')}
            </AppButton>
        </Row>
    </div>
    {#if isColorPickerOpen}
        <ColorPicker
            style="right:0.8rem;top:0.5rem"
            value={track.color}
            onChange={(color) => {
                onChange(track.set({color}))
                isColorPickerOpen = false
                vsrgComposerStore.emitEvent('colorChange')
            }}
        />
    {/if}
{/if}

// src/components/VsrgComposer/VsrgTrackSettings.tsx
import { InstrumentSelect } from "$cmp/Inputs/InstrumentSelect"
import { AppButton } from "$cmp/Inputs/AppButton"
import { VsrgTrack } from "$lib/Songs/VsrgSong"
import { FaTrash } from "react-icons/fa"
import { PitchSelect } from "$cmp/Inputs/PitchSelect"
import { HelpTooltip } from "$cmp/Utility/HelpTooltip"
import { ColorPicker } from "$cmp/Inputs/ColorPicker"
import { useState } from "react"
import Color from "color"
import { vsrgComposerStore } from "$stores/VsrgComposerStore"
import { Pitch } from "$/Config"

interface TrackSelectorProps {
    track: VsrgTrack
    onSave: () => void
    onDelete: () => void
    onChange: (track: VsrgTrack) => void
}

export function VsrgTrackSettings({ track, onSave, onDelete, onChange }: TrackSelectorProps) {
    const [isColorPickerOpen, setIsColorPickerOpen] = useState(false)
    if (!track) return null
    return <>
        <div className="vsrg-floating-settings box-shadow">
            <div className="row-centered space-between">
                Track name
                <input
                    type="text"
                    maxLength={50}
                    className="input"
                    style={{ width: '7.4rem' }}
                    value={track.instrument.alias}
                    onChange={e => {
                        track.instrument.set({ alias: e.target.value })
                        onChange(track)
                    }}
                    placeholder={track.instrument.name}
                />
            </div>
            <div className="row-centered space-between" style={{ marginTop: '0.4rem' }}>
                Instrument
                <InstrumentSelect
                    style={{ width: '8rem' }}
                    selected={track.instrument.name}
                    onChange={(name) => {
                        track.instrument.set({ name })
                        onChange(track)
                    }}
                />
            </div>
            <div className="row-centered space-between" style={{ marginTop: '0.4rem' }}>
                Pitch
                <PitchSelect
                    style={{ width: '8rem' }}
                    selected={track.instrument.pitch as Pitch}
                    onChange={(pitch) => {
                        track.instrument.set({ pitch })
                        onChange(track)
                    }}
                >
                    <option value="">
                        Use song pitch
                    </option>
                </PitchSelect>
            </div>
            <div className="row-centered" style={{ marginTop: '1rem', alignItems: "center" }}>
                Volume
                <span style={{
                    marginLeft: "0.4rem",
                    width: '3rem',
                    ...(track.instrument.volume > 100
                        && { color: `hsl(0, ${-40 + track.instrument.volume}%, 61%)`, marginLeft: "0.4rem" })
                }}
                >
                    {track.instrument.volume}%
                </span>
                <HelpTooltip
                    buttonStyle={{ width: '1.2rem', height: '1.2rem' }}
                    width={10}
                >
                    If you hear distortion, reduce the volume
                </HelpTooltip>
            </div>
            <div className="row-centered">
                <input
                    type="range"
                    style={{ flex: '1' }}
                    min={0}
                    max={125}
                    value={track.instrument.volume}
                    onChange={e =>{
                        track.instrument.set({ volume: parseInt(e.target.value) })
                        onChange(track)
                    }}
                />
            </div>
            <div className="column">
                <div className="row-centered space-between">
                    Color
                    <AppButton
                        onClick={() => setIsColorPickerOpen(true)}
                        ariaLabel='Change color'
                        style={{
                            backgroundColor: track.color,
                            color: Color(track.color).isDark() ? '#fff' : '#000',
                        }}
                    >
                        Change
                    </AppButton>
                </div>
            </div>
            <div className='row space-between' style={{ marginTop: '0.4rem' }}>
                <AppButton
                    className="row-centered"
                    style={{ padding: '0.4rem', width: 'fit-content' }}
                    onClick={onDelete}
                >
                    <FaTrash color="var(--red)" style={{ marginRight: '0.3rem' }} />
                    Delete
                </AppButton>
                <AppButton
                    onClick={onSave}
                    style={{ padding: '0.4rem', width: 'fit-content' }}
                >
                    Ok
                </AppButton>
            </div>
        </div>
        {isColorPickerOpen &&
            <ColorPicker
                style={{
                    right: '0.8rem',
                    top: '0.5rem',
                }}
                value={track.color}
                onChange={color => {
                    onChange(track.set({ color }))
                    setIsColorPickerOpen(false)
                    vsrgComposerStore.emitEvent("colorChange")
                }}
            />
        }
    </>
}
