// src/lib/components/utility/BodyDropper.svelte
<script lang="ts">
    import {onMount} from 'svelte'
    import {t} from '$i18n/binding.svelte'

    // `.drag-n-drop` CSS lives in global App.css.
    export interface DroppedFile<T = ArrayBuffer | object | string> {
        data: T
        file: File
    }

    let {
        as,
        onHoverChange,
        onDrop,
        onError,
        showDropArea = false,
        dropAreaStyle = '',
    }: {
        as: 'json' | 'text' | 'buffer'
        onHoverChange?: (isHovering: boolean) => void
        onDrop: (files: DroppedFile[]) => void
        onError?: (error: unknown) => void
        showDropArea?: boolean
        dropAreaStyle?: string
    } = $props()

    let isHovering = $state(false)
    let debouncedIsHovering = $state(false)

    $effect(() => {
        void isHovering
        const handle = setTimeout(() => {
            debouncedIsHovering = isHovering
        }, 50)
        return () => clearTimeout(handle)
    })

    $effect(() => {
        onHoverChange?.(debouncedIsHovering)
    })

    function hasFiles(event: DragEvent): boolean {
        return event.dataTransfer?.types.includes('Files') ?? false
    }

    function resetDrag() {
        isHovering = false
    }

    function handleDragOver(event: DragEvent) {
        event.preventDefault()
        if (!hasFiles(event)) return
        isHovering = true
    }

    function handleDrag(event: DragEvent) {
        if (!hasFiles(event)) return
        event.preventDefault()
        isHovering = true
    }

    async function handleDrop(event: DragEvent) {
        resetDrag()
        event.preventDefault()
        const files = Array.from(event.dataTransfer?.files ?? [])
        const promises: Promise<DroppedFile>[] = files.map(file => new Promise((resolve, reject) => {
            const fileReader = new FileReader()

            function handleLoad() {
                try {
                    const value = fileReader.result as string | ArrayBuffer
                    resolve({
                        data: as === 'json' ? JSON.parse(value as string) : value,
                        file
                    })
                } catch (e) {
                    reject(e)
                }
            }

            try {
                fileReader.addEventListener('loadend', handleLoad, {once: true})
                if (as === 'text' || as === 'json') fileReader.readAsText(file)
                if (as === 'buffer') fileReader.readAsArrayBuffer(file)
            } catch (e) {
                reject(e)
            }
        }))
        try {
            const result = await Promise.all(promises)
            onDrop(result)
        } catch (e) {
            console.error(e)
            onError?.(e)
        }
    }

    onMount(() => {
        window.addEventListener('drop', handleDrop)
        window.addEventListener('dragenter', handleDrag)
        window.addEventListener('dragleave', resetDrag)
        window.addEventListener('dragover', handleDragOver)
        return () => {
            window.removeEventListener('drop', handleDrop)
            window.removeEventListener('dragenter', handleDrag)
            window.removeEventListener('dragleave', resetDrag)
            window.removeEventListener('dragover', handleDragOver)
        }
    })
</script>

{#if showDropArea && debouncedIsHovering}
    <div class="drag-n-drop" style={dropAreaStyle}>
        {t('home:drop_files_here')}
    </div>
{/if}

// src/components/BodyDropper.tsx
import { memo, useCallback, useEffect, useState } from "react"

export interface DroppedFile<T> {
    data: Buffer | object | string | T,
    file: File
}

interface BodyDropperProps<T> {
    as: 'json' | 'text' | 'buffer'
    onHoverChange?: (isHovering: boolean) => void
    onDrop: (files: DroppedFile<T>[]) => void,
    onError?: (error: any) => void,
    showDropArea?: boolean
    dropAreaStyle?: any
}

function hasFiles(event: DragEvent) {
    return event?.dataTransfer?.types.includes('Files')
}


function BodyDropperComponent<T>({ onHoverChange, onDrop, onError, as, showDropArea = false ,dropAreaStyle = {}}: BodyDropperProps<T>) {
    const [isHovering, setIsHovering] = useState(false)
    const resetDrag = useCallback(() => {

        setIsHovering(false)
        onHoverChange?.(false)
    }, [onHoverChange])

    const handleDragOver = useCallback((e: DragEvent) => {
        e.preventDefault()
        if(!hasFiles(e)) return
        setIsHovering(true)
        onHoverChange?.(true)
    }, [onHoverChange])

    const handleDrag = useCallback((e: DragEvent) => {
        if(!hasFiles(e)) return
        e.preventDefault()
        setIsHovering(true)
        onHoverChange?.(true)
    }, [onHoverChange])

    const handleDrop = useCallback(async (e: DragEvent) => {
        resetDrag()
        e.preventDefault()
        const promises: Promise<DroppedFile<T>>[] = Array.from(e.dataTransfer?.files || []).map((file: File) => {
            return new Promise((resolve, reject) => {
                const fileReader = new FileReader()
                function handleLoad() {
                    try {
                        const value = fileReader.result as any
                        resolve({
                            data: as === 'json' ? JSON.parse(value) : value,
                            file: file
                        })
                    } catch (e: any) {

                        reject(e)
                    }
                }
                try {
                    fileReader.addEventListener('loadend', handleLoad, { once: true })
                    if (as === 'text' || as === 'json') fileReader.readAsText(file)
                    if (as === 'buffer') fileReader.readAsArrayBuffer(file)
                } catch (e: any) {
                    reject(e)
                }
            })
        })
        try {
            const result = await Promise.all(promises)
            onDrop(result)
        } catch (e) {
            console.error(e)
            onError?.(e)
        }

    }, [resetDrag, onDrop, onError, as])
    useEffect(() => {
        document.body.addEventListener('drop', handleDrop)
        return () => document.body.removeEventListener('drop', handleDrop)
    }, [handleDrop])

    useEffect(() => {
        document.body.addEventListener('dragenter', handleDrag)
        document.body.addEventListener('dragleave', resetDrag)
        document.body.addEventListener('dragover', handleDragOver)
        return () => {
            document.body.removeEventListener('dragenter', handleDrag)
            document.body.removeEventListener('dragleave', resetDrag)
            document.body.removeEventListener('dragover', handleDragOver)
        }
    }, [resetDrag, handleDrag, handleDragOver])
    return <>
        {showDropArea && <DropHoverHinter isHovering={isHovering} style={dropAreaStyle}>
            Drop files here
        </DropHoverHinter>
        }
    </>
}
interface HoverHinterProps {
    isHovering: boolean
    children: React.ReactNode
    style: any
}
export const DropHoverHinter = memo(({ isHovering, children, style }: HoverHinterProps) => {
    return <>
        {isHovering && <div className='drag-n-drop' style={style}>
            {children}
        </div>}
    </>
}, (p, n) => {
    return p.children === n.children && p.isHovering === n.isHovering
})

export const BodyDropper = memo(BodyDropperComponent, (p, n) => {
    return p.as === n.as && p.onDrop === n.onDrop && p.onError === n.onError && p.onHoverChange === n.onHoverChange && p.showDropArea === n.showDropArea
}) as typeof BodyDropperComponent
