// src/lib/components/utility/Tooltip.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'
    import type {TooltipPosition} from './tooltip'

    // CSS (.tooltip, .tooltip-<position>, .has-tooltip) lives in global
    // App.css - no component <style> here.
    let {children, position = 'bottom', style}: {children: Snippet, position?: TooltipPosition, style?: string} = $props()
</script>

<span class={['tooltip', `tooltip-${position}`]} {style}>
    {@render children()}
</span>

// src/components/Tooltip.tsx

interface TooltipProps{
    children: React.ReactNode;
    position?: 'top' | 'bottom' | 'left' | 'right'
}
export function Tooltip({children, position = 'bottom'}: TooltipProps) {
    return <span className={`tooltip tooltip-${position}`}>
        {children}
    </span>
}

export function hasTooltip(text?:string){
    return text ? 'has-tooltip' : '';
}
