// src/lib/components/pages/Player/PlayerPagesRenderer.svelte
<script lang="ts">
    import {game} from '$game'
    import SheetFrame from '$cmp/pages/SheetVisualizer/SheetFrame.svelte'
    import {playerControlsStore} from '$stores/PlayerControlsStore.svelte'
    import {ThemeProvider as theme} from '$core/theme/ThemeProvider.svelte'
    import './VisualSheet.css'

    // RecordedSong.ts and VisualSong.ts each declare their own, unrelated Chunk class - SheetFrame's
    // chunk prop is typed against VisualSong's, but the value passed below is a RecordedSong Chunk.
    // TypeScript accepts this structurally; don't assume the two types stay in sync.
    let {columns}: {columns: number} = $props()

    const layoutType = game.settings.defaultNoteNameType.sheetVisualizer
</script>

{#if playerControlsStore.pagesState.pages.length > 0}
    <div
        class="player-chunks-page"
        style="grid-template-columns:repeat({columns}, 1fr)"
    >
        {#each playerControlsStore.pagesState.currentPage as chunk, i (i)}
            <SheetFrame
                keyboardLayout={layoutType}
                {theme}
                selected={i === playerControlsStore.pagesState.currentChunkIndex}
                {chunk}
                rows={3}
                hasText={false}
            />
        {/each}
    </div>
{/if}

// src/components/Player/PlayerPagesRenderer.tsx
import { SheetFrame } from "$cmp/SheetVisualizer/SheetFrame"
import { useObservableObject } from "$lib/Hooks/useObservable"
import { useTheme } from "$lib/Hooks/useTheme"
import { memo } from "react"
import { playerControlsStore } from "$stores/PlayerControlsStore"
import { APP_NAME } from "$config"
import s from './VisualSheet.module.css'

const layoutType =  APP_NAME === 'Genshin' ? 'Keyboard layout' : 'ABC'

function _PlayerVisualSheetRenderer(){
    const pagesState = useObservableObject(playerControlsStore.pagesState)
    const [theme] = useTheme()
    return <>
    {pagesState.pages.length > 0 &&
        <div className={s['player-chunks-page']}>
            {pagesState.currentPage?.map((e, i) =>
                <SheetFrame
                    key={i}
                    keyboardLayout={layoutType}
                    theme={theme}
                    selected={i === pagesState.currentChunkIndex}
                    chunk={e}
                    rows={3}
                    hasText={false}
                />
            )}
        </div>
    }
    </>
}
export const PlayerVisualSheetRenderer = memo(_PlayerVisualSheetRenderer, () => true)
