// src/lib/components/utility/HelpTooltip.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'

    // `.help-tooltip*` CSS lives in global App.css.
    let {
        children,
        maxWidth = 18,
        buttonStyle = '',
        parentStyle = '',
        width,
        position = 'right',
    }: {
        children: Snippet
        maxWidth?: number
        width?: number
        position?: 'left' | 'right' | 'middle'
        buttonStyle?: string
        parentStyle?: string
    } = $props()

    const positionMap = {left: '-100%', right: '0', middle: '-50%'}

    let buttonEl: HTMLButtonElement | undefined = $state()
</script>

<div class="help-tooltip" style="position:relative;{parentStyle}">
    <button
        bind:this={buttonEl}
        class="help-tooltip-button"
        style={buttonStyle}
        aria-label="Help"
        onclick={() => buttonEl?.focus()}
    >
        <svg
            stroke="currentColor"
            fill="currentColor"
            stroke-width="0"
            viewBox="0 0 24 24"
            style="width:100%;height:100%"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path fill="none" d="M0 0h24v24H0z" />
            <path
                d="M11 18h2v-2h-2v2zm1-16C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm0-14c-2.21 0-4 1.79-4 4h2c0-1.1.9-2 2-2s2 .9 2 2c0 2-3 1.75-3 5h2c0-2.25 3-2.5 3-5 0-2.21-1.79-4-4-4z"
            />
        </svg>
    </button>
    <div
        class="help-tooltip-content"
        style="translate:{positionMap[position]};max-width:{maxWidth}rem;width:{width !== undefined ? `${width}rem` : 'max-content'}"
    >
        {@render children()}
    </div>
</div>

// src/components/shared/Utility/HelpTooltip.tsx
import {useRef} from 'react';
import {MdHelpOutline} from 'react-icons/md';

interface HelpTooltipProps {
    children: React.ReactNode;
    maxWidth?: number
    width?: number
    position?: 'left' | 'right' | 'middle'
    buttonStyle?: React.CSSProperties
    parentStyle?: React.CSSProperties
}

const positionMap = {
    left: '-100%',
    right: '0',
    middle: '-50%'
}

export function HelpTooltip({children, maxWidth = 18, buttonStyle, parentStyle, width, position = 'right'}: HelpTooltipProps) {
    const ref = useRef<HTMLButtonElement>(null)
    return <div className="help-tooltip" style={{
        position: 'relative',
        ...parentStyle
    }}>
        <button
            ref={ref}
            className='help-tooltip-button'
            style={buttonStyle}
            aria-label={'Help'}
            //Safari focus workaround
            onClick={() => ref.current?.focus()}
        >
            <MdHelpOutline style={{
                width: '100%',
                height: '100%'
            }}/>
        </button>
        <div className="help-tooltip-content"
             style={{
                 translate: positionMap[position],
                 maxWidth: `${maxWidth}rem`,
                 width: width !== undefined ? `${width}rem` : 'max-content',
             }}
        >
            {children}
        </div>
    </div>
}
