// src/lib/components/utility/Tooltip.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'
    import type {TooltipPosition} from './tooltip'

    // CSS (.tooltip, .tooltip-<position>, .has-tooltip) lives in global
    // App.css - no component <style> here.
    let {children, position = 'bottom', style}: {children: Snippet, position?: TooltipPosition, style?: string} = $props()
</script>

<span class={['tooltip', `tooltip-${position}`]} {style}>
    {@render children()}
</span>

// src/components/shared/Utility/Tooltip.tsx
export type TooltipPosition = 'top' | 'bottom' | 'left' | 'right'

interface TooltipProps {
    children: React.ReactNode;
    position?: TooltipPosition
    style?: React.CSSProperties
}

export function Tooltip({children, position = 'bottom', style}: TooltipProps) {
    return <span className={`tooltip tooltip-${position}`} style={style}>
        {children}
    </span>
}

export function hasTooltip(text?: string | boolean) {
    return text ? 'has-tooltip' : '';
}
