// src/pages/theme/index.tsx
import {useCallback, useState} from "react";
import {BaseTheme, defaultThemes, SerializedTheme, ThemeKeys, ThemeProvider} from "$stores/ThemeStore/ThemeProvider";
import {AppButton} from "$cmp/shared/Inputs/AppButton";
import {FileElement, FilePicker} from "$cmp/shared/Inputs/FilePicker"
import Player from "$pages/player";
import Composer from "$pages/composer";
import {asyncConfirm, asyncPrompt} from "$cmp/shared/Utility/AsyncPrompts";
import {ThemePropriety} from "$cmp/pages/Theme/ThemePropriety";
import cloneDeep from 'lodash.clonedeep'
import {ThemePreview} from "$cmp/pages/Theme/ThemePreview";
import {FaPlus} from "react-icons/fa";
import {logger} from "$stores/LoggerStore";
import {ThemeInput} from "$cmp/pages/Theme/ThemeInput";
import {useTheme} from "$lib/Hooks/useTheme";
import {AppBackground} from "$cmp/shared/pagesLayout/AppBackground";
import {PageMetadata} from "$cmp/shared/Miscellaneous/PageMetadata";
import {DefaultPage} from "$cmp/shared/pagesLayout/DefaultPage";
import {useObservableArray} from "$lib/Hooks/useObservable";
import {themeStore} from "$stores/ThemeStore/ThemeStore";
import {fileService} from "$lib/Services/FileService";
import {useTranslation} from "react-i18next";


function ThemePage() {
    const {t} = useTranslation(["theme", "home", "common"])
    const [theme] = useTheme()
    const userThemes = useObservableArray<SerializedTheme>(themeStore.themes)
    const [selectedProp, setSelectedProp] = useState('')
    const [selectedPagePreview, setSelectedPagePreview] = useState<"player" | "composer">("player")

    async function handleChange(name: ThemeKeys, value: string) {
        if (!ThemeProvider.isEditable()) {
            if (value === ThemeProvider.get(name).toString()) return
            const themeName = await asyncPrompt('Creating a new theme from this default theme, write the name:')
            if (themeName === null) return
            await cloneTheme(themeName)
        }
        ThemeProvider.set(name, value)
        await ThemeProvider.save()
    }

    async function handlePropReset(key: ThemeKeys) {
        ThemeProvider.reset(key)
        await ThemeProvider.save()
    }

    async function handleImport(files: FileElement<SerializedTheme>[]) {
        for (const file of files) {
            const theme = file.data as SerializedTheme
            try {
                await fileService.importAndLog(theme)
            } catch (e) {
                logImportError()
            }
        }
    }

    const logImportError = useCallback((error?: any) => {
        if (error) console.error(error)
        logger.error(t('error_importing_theme'), 4000)
    }, [t])

    async function cloneTheme(name: string) {
        const theme = new BaseTheme(name)
        theme.state = cloneDeep(ThemeProvider.state)
        theme.state.other.name = name
        theme.state.editable = true
        await addNewTheme(theme)
    }

    async function handleNewThemeClick() {
        const name = await asyncPrompt(t('choose_theme_name'))
        if (name !== null && name !== undefined) {
            const theme = new BaseTheme(name)
            await addNewTheme(theme)
        }
    }

    async function addNewTheme(newTheme: BaseTheme) {
        const theme = newTheme.serialize()
        const id = await themeStore.addTheme(theme)
        theme.id = id
        ThemeProvider.loadFromJson(theme, id)
        ThemeProvider.save()
        return id
    }

    async function handleThemeDelete(theme: SerializedTheme) {
        if (await asyncConfirm(t('confirm_delete_theme',{theme_name: theme.other.name}))) {
            if (ThemeProvider.getId() === theme.id) {
                ThemeProvider.wipe()
            }
            await themeStore.removeThemeById(theme.id!)
        }
    }

    return <DefaultPage>
        <PageMetadata text={t('home:themes_name')}
                      description="Change the theme of the app, set all colors and backgrounds, make elements translucent and share/import themes"/>
        <div style={{display: 'flex', alignItems: 'center'}}>
            <FilePicker onPick={handleImport} as='json' onError={logImportError}>
                <AppButton style={{margin: '0.25rem'}}>
                    {t('import_theme')}
                </AppButton>
            </FilePicker>
            <div style={{marginLeft: '1rem'}}>
                {ThemeProvider.getOther('name')}
            </div>
        </div>
        <div style={{marginTop: '2.2rem'}}>
        </div>
        {theme.toArray().map(e =>
            <ThemePropriety
                {...e}
                key={e.name}
                isSelected={selectedProp === e.name}
                canReset={ThemeProvider.isEditable()}
                isModified={!theme.isDefault(e.name)}
                onChange={handleChange}
                setSelectedProp={setSelectedProp}
                handlePropReset={handlePropReset}
            />
        )}
        <ThemeInput
            name={t('theme_prop.background_image')}
            value={theme.getOther('backgroundImageMain')}
            disabled={!ThemeProvider.isEditable()}
            onChange={(e) => ThemeProvider.setBackground(e, 'Main')}
        />
        <ThemeInput
            name={t('theme_prop.composer_background_image')}
            value={theme.getOther('backgroundImageComposer')}
            disabled={!ThemeProvider.isEditable()}
            onChange={(e) => ThemeProvider.setBackground(e, 'Composer')}
        />
        <ThemeInput
            name={t('theme_prop.theme_name')}
            value={theme.getOther('name')}
            disabled={!ThemeProvider.isEditable()}
            onChange={(e) => ThemeProvider.setOther('name', e)}
            onLeave={() => ThemeProvider.save()}
        />
        <div style={{textAlign: 'center', marginTop: '1rem'}}>
            <span style={{color: 'var(--red)'}}>
                {t('common:warning')}
            </span>: {t('opaque_performance_warning')}
        </div>
        <div style={{fontSize: '1.5rem', marginTop: '2rem'}}>
            {t('your_themes')}
        </div>
        <div className="theme-preview-wrapper">
            {userThemes.map(theme =>
                <ThemePreview
                    onDelete={handleThemeDelete}
                    current={theme.id === ThemeProvider.getId()}
                    key={theme.id}
                    theme={theme}
                    downloadable={true}
                    onClick={(theme) => {
                        ThemeProvider.loadFromTheme(theme)
                        ThemeProvider.save()
                    }}
                />
            )}
            <button className="new-theme" onClick={handleNewThemeClick}>
                <FaPlus size={30}/>
                {t('new_theme')}
            </button>
        </div>
        <div style={{fontSize: '1.5rem', marginTop: '2rem'}}>
            {t('default_themes')}
        </div>
        <div className="theme-preview-wrapper">
            {defaultThemes.map(theme =>
                <ThemePreview
                    key={theme.id}
                    theme={theme}
                    current={theme.id === ThemeProvider.getId()}
                    onClick={(theme) => {
                        ThemeProvider.loadFromTheme(theme)
                        ThemeProvider.save()
                    }}
                />
            )}
        </div>
        <div style={{fontSize: '1.5rem', marginTop: '2rem'}}>
            {t('preview')}
        </div>
        <div className="theme-app-preview">
            <AppButton
                className="box-shadow"
                toggled={true}
                style={{position: 'absolute', right: 0, top: 0, zIndex: 90}}
                onClick={() => setSelectedPagePreview(selectedPagePreview === 'composer' ? 'player' : 'composer')}
            >
                {selectedPagePreview === 'composer' ? t('view_player') : t('view_composer')}
            </AppButton>
            {selectedPagePreview === "player" &&
                <AppBackground page="Main">
                    <Player inPreview={true}/>
                </AppBackground>
            }
            {selectedPagePreview === "composer" &&
                <AppBackground page="Composer">
                    <Composer inPreview={true}/>
                </AppBackground>
            }
        </div>
        {/*Keep this at the bottom because it gets overwritten by the preview apps above */}
        <PageMetadata text={t('home:themes_name')}
                      description="Change the app theme, set the different colors, backgrounds, opacity and customisations"/>
    </DefaultPage>
}


export default ThemePage

// src/routes/theme/+page.svelte
<script lang="ts">
    import {onMount} from 'svelte'
    import cloneDeep from 'lodash.clonedeep'
    import DefaultPage from '$cmp/shell/DefaultPage.svelte'
    import PageMetadata from '$cmp/shell/PageMetadata.svelte'
    import AppButton from '$cmp/inputs/AppButton.svelte'
    import FilePicker, {type FileElement} from '$cmp/inputs/FilePicker.svelte'
    import AppBackground from '$cmp/theme/AppBackground.svelte'
    import Player from '$cmp/pages/Player/Player.svelte'
    import Composer from '$cmp/pages/Composer/Composer.svelte'
    import ThemePropriety from '$cmp/pages/theme/ThemePropriety.svelte'
    import ThemeInput from '$cmp/pages/theme/ThemeInput.svelte'
    import ThemePreview from '$cmp/pages/theme/ThemePreview.svelte'
    import {
        BaseTheme,
        ThemeProvider as theme,
        defaultThemes,
        type SerializedTheme,
        type ThemeKeys
    } from '$core/theme/ThemeProvider.svelte'
    import {asyncConfirm, asyncPrompt} from '$stores/AsyncPromptStore.svelte'
    import {logger} from '$stores/LoggerStore.svelte'
    import {themeStore} from '$stores/ThemeStore.svelte'
    import {fileService} from '$core/Services/FileService'
    import {setPageVisited} from '$stores/PageVisitStore.svelte'
    import {t} from '$i18n/binding.svelte'

    onMount(() => {
        setPageVisited('theme')
    })

    let selectedProp = $state<ThemeKeys | ''>('')
    let selectedPagePreview = $state<'player' | 'composer'>('player')

    async function handleChange(name: ThemeKeys, value: string) {
        if (!theme.isEditable()) {
            if (value === theme.get(name).toString()) return
            const themeName = await asyncPrompt('Creating a new theme from this default theme, write the name:')
            if (themeName === null) return
            await cloneTheme(themeName)
        }
        theme.set(name, value)
        await theme.save()
    }

    async function handlePropReset(key: ThemeKeys) {
        theme.reset(key)
        await theme.save()
    }

    async function handleImport(files: FileElement<SerializedTheme>[]) {
        for (const file of files) {
            const importedTheme = file.data
            try {
                await fileService.importAndLog(importedTheme)
            } catch (e) {
                logImportError(e)
            }
        }
    }

    function logImportError(error?: unknown) {
        if (error) console.error(error)
        logger.error(t('theme:error_importing_theme'), 4000)
    }

    async function cloneTheme(name: string) {
        const newTheme = new BaseTheme(name)
        newTheme.state = cloneDeep(theme.state)
        newTheme.state.other.name = name
        newTheme.state.editable = true
        await addNewTheme(newTheme)
    }

    async function handleNewThemeClick() {
        const name = await asyncPrompt(t('theme:choose_theme_name'))
        if (name !== null && name !== undefined) {
            const newTheme = new BaseTheme(name)
            await addNewTheme(newTheme)
        }
    }

    async function addNewTheme(newTheme: BaseTheme) {
        const serialized = newTheme.serialize()
        const id = await themeStore.addTheme(serialized)
        serialized.id = id
        theme.loadFromJson(serialized, id)
        theme.save()
        return id
    }

    async function handleThemeDelete(savedTheme: SerializedTheme) {
        if (await asyncConfirm(t('theme:confirm_delete_theme', {theme_name: savedTheme.other.name}))) {
            if (theme.getId() === savedTheme.id) {
                theme.wipe()
            }
            await themeStore.removeThemeById(savedTheme.id!)
        }
    }

    function loadSavedTheme(savedTheme: SerializedTheme) {
        theme.loadFromTheme(savedTheme)
        theme.save()
    }
</script>

<DefaultPage>
    <PageMetadata
        text={t('home:themes_name')}
        description="Change the theme of the app, set all colors and backgrounds, make elements translucent and share/import themes"
    />
    <div style="display:flex;align-items:center">
        <FilePicker onPick={handleImport} as="json" onError={logImportError}>
            <AppButton style="margin:0.25rem">
                {t('theme:import_theme')}
            </AppButton>
        </FilePicker>
        <div style="margin-left:1rem">
            {theme.getOther('name')}
        </div>
    </div>
    <div style="margin-top:2.2rem"></div>
    {#each theme.toArray() as prop (prop.name)}
        <ThemePropriety
            name={prop.name}
            value={prop.value}
            isSelected={selectedProp === prop.name}
            canReset={theme.isEditable()}
            isModified={!theme.isDefault(prop.name)}
            onChange={handleChange}
            setSelectedProp={(name) => (selectedProp = name)}
            {handlePropReset}
        />
    {/each}
    <ThemeInput
        name={t('theme:theme_prop.background_image')}
        value={theme.getOther('backgroundImageMain')}
        disabled={!theme.isEditable()}
        onChange={(e) => theme.setBackground(e, 'Main')}
    />
    <ThemeInput
        name={t('theme:theme_prop.composer_background_image')}
        value={theme.getOther('backgroundImageComposer')}
        disabled={!theme.isEditable()}
        onChange={(e) => theme.setBackground(e, 'Composer')}
    />
    <ThemeInput
        name={t('theme:theme_prop.theme_name')}
        value={theme.getOther('name')}
        disabled={!theme.isEditable()}
        onChange={(e) => theme.setOther('name', e)}
        onLeave={() => theme.save()}
    />
    <div style="text-align:center;margin-top:1rem">
        <span style="color:var(--red)">{t('common:warning')}</span>: {t('theme:opaque_performance_warning')}
    </div>
    <div style="font-size:1.5rem;margin-top:2rem">
        {t('theme:your_themes')}
    </div>
    <div class="theme-preview-wrapper">
        {#each themeStore.themes as savedTheme (savedTheme.id)}
            <ThemePreview
                onDelete={handleThemeDelete}
                current={savedTheme.id === theme.getId()}
                theme={savedTheme}
                downloadable={true}
                onClick={loadSavedTheme}
            />
        {/each}
        <button class="new-theme" onclick={handleNewThemeClick}>
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 448 512" height="30" width="30" xmlns="http://www.w3.org/2000/svg"><path d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"/></svg>
            {t('theme:new_theme')}
        </button>
    </div>
    <div style="font-size:1.5rem;margin-top:2rem">
        {t('theme:default_themes')}
    </div>
    <div class="theme-preview-wrapper">
        {#each defaultThemes as savedTheme (savedTheme.id)}
            <ThemePreview theme={savedTheme} current={savedTheme.id === theme.getId()} onClick={loadSavedTheme} />
        {/each}
    </div>
    <div style="font-size:1.5rem;margin-top:2rem">
        {t('theme:preview')}
    </div>
    <div class="theme-app-preview">
        <AppButton
            class="box-shadow"
            toggled={true}
            style="position:absolute;right:0;top:0;z-index:90"
            onclick={() => (selectedPagePreview = selectedPagePreview === 'composer' ? 'player' : 'composer')}
        >
            {selectedPagePreview === 'composer' ? t('theme:view_player') : t('theme:view_composer')}
        </AppButton>
        {#if selectedPagePreview === 'player'}
            <AppBackground page="Main">
                <Player inPreview />
            </AppBackground>
        {:else}
            <AppBackground page="Composer">
                <Composer inPreview />
            </AppBackground>
        {/if}
    </div>
    <!-- QUIRK (load-bearing, read before restructuring this page): must stay at the bottom, after
         both preview branches. Svelte compiles a <title> inside <svelte:head> to a plain
         document.title assignment in that component's own mount effect, so when several
         PageMetadata instances mount together, the LAST one to run wins - this trailing instance
         being last is what makes "Themes" the final title on a fresh load.
         That alone isn't enough once toggling `selectedPagePreview` is possible: neither preview
         branch is a stub, so each one has its OWN PageMetadata too. Swapping the {#if} branch
         re-runs the newly-mounted branch's title effect, but this trailing PageMetadata is
         already mounted with an unchanged `text` prop, so its own effect never re-runs - the tab
         title stays stuck on whatever the branch just switched to. {#key selectedPagePreview}
         below forces this PageMetadata to unmount+remount (re-running its title effect) on every
         toggle, strictly after the branch swap in template order, restoring "Themes". -->
    {#key selectedPagePreview}
        <PageMetadata
            text={t('home:themes_name')}
            description="Change the app theme, set the different colors, backgrounds, opacity and customisations"
        />
    {/key}
</DefaultPage>
