// src/lib/components/settings/InstrumentInput.svelte
<script lang="ts">
    import type {InstrumentName} from '$core/types'
    import type {SettingUpdate, SettingUpdateKey, SettingVolumeUpdate, SettingsInstrument} from '$core/types/SettingsPropriety'
    import InstrumentSelect from '../inputs/InstrumentSelect.svelte'

    // Old: src/components/shared/Settings/InstrumentInput.tsx
    // Old declared a `theme: Theme` prop but never referenced it anywhere in its own body (its
    // <InstrumentSelect> call didn't pass a theme prop either, even in old) - a pre-existing dead
    // prop, dropped here the same way `inputs/Select.svelte` already dropped its own dead
    // `className` prop (Phase 3 Task 5 precedent).
    let {
        data,
        volume,
        onVolumeChange,
        onVolumeComplete,
        onInstrumentPick,
        objectKey,
        instrument,
    }: {
        data: SettingsInstrument
        volume: number
        instrument: InstrumentName
        objectKey: SettingUpdateKey
        onVolumeChange: (value: number) => void
        onVolumeComplete: (data: SettingVolumeUpdate) => void
        onInstrumentPick: (data: SettingUpdate) => void
    } = $props()

    function handleVolumeChange(e: Event & {currentTarget: EventTarget & HTMLInputElement}) {
        onVolumeChange(Number(e.currentTarget.value))
    }

    function handleVolumePick() {
        onVolumeComplete({
            key: objectKey,
            value: volume
        })
    }

    function handleInstrument(ins: InstrumentName) {
        onInstrumentPick({
            key: objectKey,
            data: {...data, value: ins}
        })
    }
</script>

<div class="instrument-picker">
    <InstrumentSelect
        selected={instrument}
        onChange={handleInstrument}
        className="select"
        style="text-align:left;padding-left:0.4rem;"
    />
    <input
        type="range"
        min={1}
        max={100}
        value={volume}
        onchange={handleVolumeChange}
        onpointerup={handleVolumePick}
    />
</div>

<style>
    .instrument-picker {
        display: flex;
        flex-direction: column;
        width: 8rem;
    }

    .instrument-picker input[type='range'] {
        margin-top: 0.2rem;
    }
</style>

// src/components/Settings/InstrumentInput.tsx
import { ChangeEvent } from "react"
import { ThemeStore } from "stores/ThemeStore"
import { InstrumentName } from "types/GeneralTypes"
import { SettingsInstrument, SettingUpdateKey } from "types/SettingsPropriety"

interface InstrumentInputProps{
    data: SettingsInstrument,
    theme: ThemeStore,
    volume: number, 
    instrument: string,
    objectKey: SettingUpdateKey,
    onVolumeChange: (value: number) => void,
    onVolumeComplete: (data: {
        value: number
        key: SettingUpdateKey
    }) => void,
    onInstrumentPick: (data: {
        key: SettingUpdateKey, 
        data: SettingsInstrument
    }) => void
}

export function InstrumentInput({data,volume, onVolumeChange, onVolumeComplete, onInstrumentPick, objectKey, instrument, theme}: InstrumentInputProps) {
    function handleVolumeChange(e: ChangeEvent<HTMLInputElement>){
        onVolumeChange(Number(e.target.value))
    }
    function handleVolumePick(){
        onVolumeComplete({
            key: objectKey,
            value: volume
        })
    }
    function handleInstrument(e: ChangeEvent<HTMLSelectElement>){
        onInstrumentPick({
            key: objectKey,
            data: { ...data, value: e.target.value as InstrumentName }
        })
    }

    return <div className="instrument-picker">
        <select value={instrument}
            style={{
                backgroundImage: `url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' height='24' viewBox='0 0 24 24' width='24' fill='${theme.getText('primary').hex().replace('#','%23')}'><path d='M0 0h24v24H0z' fill='none'/><path d='M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z'/></svg>")`
            }}
            onChange={handleInstrument}
        >
            {data.options.map(e => {
                return <option value={e} key={e}>{e}</option>
            })}
        </select>
        <input
            type="range"
            min={1}
            max={100}
            value={volume}
            onChange={handleVolumeChange}
            onPointerUp={handleVolumePick}
        />
    </div>
}
