// src/components/shared/layout/Grid.tsx
import {MaybeChildren, Stylable} from "$lib/UtilTypes";


interface GridProps extends Stylable {
    gap?: string;
    columns?: string;
    rows?: string;

}


export function Grid({gap, rows, columns, style, className, children}: MaybeChildren<GridProps>) {
    return <div
        style={{
            display: "grid",
            gap,
            gridTemplateColumns: columns,
            gridTemplateRows: rows,
            ...style
        }}
        className={className}
    >
        {children}
    </div>
}

// src/lib/components/layout/Grid.svelte
<script lang="ts">
    import type {Snippet} from 'svelte'

    interface GridProps {
        gap?: string
        columns?: string
        rows?: string
        className?: string
        style?: string
        children?: Snippet
    }

    let {gap, rows, columns, style = '', className, children}: GridProps = $props()

    const computedStyle = $derived([
        'display:grid',
        gap !== undefined ? `gap:${gap}` : '',
        columns !== undefined ? `grid-template-columns:${columns}` : '',
        rows !== undefined ? `grid-template-rows:${rows}` : '',
    ].filter(Boolean).join(';'))
</script>

<div style="{computedStyle};{style}" class={className}>
    {@render children?.()}
</div>
